const SB_URL='https://xtvhisddjtfnsumprgpm.supabase.co';
const PUB='sb_publishable_pYdQeWXJJjNHGwchtshJGQ_ybwDsQ5O';
const API=SB_URL+'/functions/v1/dungeon-idel-api';
const sb=window.supabase.createClient(SB_URL,PUB,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let screen='home',S=null,busy=false,session=null;
const $=s=>document.querySelector(s),fmt=n=>Number(n||0).toLocaleString('ko-KR');
const loginEmail=u=>String(u||'').trim().toLowerCase()+'@players.dungeon-idel.game';

function authMsg(text='',ok=false){const e=$('#authMsg');e.textContent=text;e.classList.toggle('ok',ok)}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),1700)}
function fam(k){return {slime:'슬라임',goblin:'고블린',troll:'트롤'}[k]||k}
function power(m){return Math.floor(m.power_base+(m.level-1)*12+Math.max(0,m.talent-80)*1.2)}
function activeOf(mid){return (S?.expeditions||[]).find(e=>e.active&&e.monster_id===mid)}
function expeditionAt(site){return (S?.expeditions||[]).filter(e=>e.active&&e.site_id===site.id)}
function lootCount(e){return Object.values(e.pending_loot||{}).reduce((a,b)=>a+Number(b||0),0)}

async function currentSession(){const {data,error}=await sb.auth.getSession();if(error)throw error;session=data.session;return session}
async function api(action,payload={}){
  const s=await currentSession();
  if(!s)throw new Error('unauthorized');
  const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUB,'Authorization':'Bearer '+s.access_token},body:JSON.stringify({action,...payload})});
  const d=await r.json().catch(()=>({error:'bad_response'}));
  if(!r.ok)throw new Error(d.error||'server_error');
  if(d.state)S=d.state;
  return d;
}
async function registerAccount(username,password){
  const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUB},body:JSON.stringify({action:'register',username,password})});
  const d=await r.json().catch(()=>({error:'bad_response'}));
  if(!r.ok)throw new Error(d.error||'register_failed');
  return d;
}

function showAuth(){close();S=null;session=null;$('#app').classList.add('hidden');$('#authGate').classList.remove('hidden');authMsg('')}
async function enterGame(){
  const s=await currentSession();
  if(!s){showAuth();return}
  $('#authGate').classList.add('hidden');$('#app').classList.remove('hidden');
  try{await api('state');render()}catch(e){if(e.message==='unauthorized'){await sb.auth.signOut();showAuth()}else{$('#serverState').textContent='서버 연결 오류';$('#serverState').className='danger';toast('서버 상태를 불러오지 못했습니다.')}}
}

function drawMonster(c,m,x,y,flip=false){const g=c.getContext('2d');g.save();g.translate(x,y);if(flip)g.scale(-1,1);const col=m.family==='slime'?'#77c98a':m.family==='goblin'?'#9cbc5d':'#82936c';g.fillStyle='#17120d';g.fillRect(-12,12,24,5);g.fillStyle=col;g.fillRect(-10,-8,20,19);g.fillRect(-7,-12,14,6);g.fillStyle='#eee3c3';g.fillRect(-5,-4,3,3);g.fillRect(3,-4,3,3);g.fillStyle='#281d16';g.fillRect(-4,-3,1,1);g.fillRect(4,-3,1,1);if(m.family==='troll'){g.fillStyle='#655846';g.fillRect(-14,-4,4,15);g.fillRect(10,-4,4,15)}g.restore()}
function battleCanvas(canvas,e){const m=S?.monsters.find(x=>x.id===e.monster_id),site=S?.sites.find(x=>x.id===e.site_id);if(!m||!site)return;const g=canvas.getContext('2d'),w=canvas.width,h=canvas.height,t=Date.now()/300;g.imageSmoothingEnabled=false;g.fillStyle='#1d2417';g.fillRect(0,0,w,h);g.fillStyle='#39462b';for(let i=0;i<20;i++)g.fillRect((i*47)%w,h-20-(i%3)*4,18,4);g.fillStyle='#765a3d';g.fillRect(w-58,34,36,44);g.fillStyle='#b9945c';g.fillRect(w-53,39,26,27);drawMonster(canvas,m,55,h-32+Math.sin(t)*2);const ex=Math.min(w-80,130)+Math.sin(t+1)*3;g.fillStyle='#d7b596';g.fillRect(ex,h-49,18,30);g.fillStyle='#75543b';g.fillRect(ex+3,h-56,12,9);g.fillStyle='#ddd4b8';g.fillRect(ex+2,h-37,4,4);g.fillStyle='#4a3c31';g.fillRect(ex+12,h-37,4,4);g.fillStyle='#e7cf78';g.font='8px monospace';g.fillText((e.battle_state&&e.battle_state.enemy)||site.enemy_names[0],Math.max(80,w-116),12);g.fillStyle=(e.battle_state&&e.battle_state.result)==='win'?'#9ddd8d':'#e59a8d';g.fillText((e.battle_state&&e.battle_state.result)==='win'?'처치!':'교전 중',10,12)}

function monsterCard(m){const e=activeOf(m.id),need=m.level*100,pct=Math.min(100,m.xp/need*100);return `<div class="card mon"><canvas class="pix" width="56" height="56" data-mid="${m.id}"></canvas><div><b>${m.name} · ${fam(m.family)}</b><div class="sub">Lv.${m.level} · 전투력 ${fmt(power(m))} · 재능 ${m.talent} · 처치 ${fmt(m.kills)}</div><div class="bar"><i style="width:${pct}%"></i></div><div class="sub">XP ${fmt(m.xp)} / ${fmt(need)}${e?` · ${S.sites.find(x=>x.id===e.site_id)?.name} 사냥 중`:''}</div></div><span class="chip ${e?'on':''}">${e?'파견 중':'대기'}</span></div>`}
function home(){const active=S.expeditions.filter(e=>e.active),pending=S.expeditions.reduce((a,e)=>a+lootCount(e),0);return `<section class="panel"><div class="title"><div><h2>${S.account?.username||'몬스터'}의 소굴</h2><div class="sub">로그아웃해도 서버에서 사냥은 계속됩니다. 다른 기기에서도 같은 계정으로 이어서 플레이할 수 있습니다.</div></div><span class="chip on">SERVER LIVE</span></div></section><section class="grid"><div class="card"><div class="sub">보유 몬스터</div><div class="big">${S.monsters.length}</div></div><div class="card"><div class="sub">사냥 중</div><div class="big">${active.length}</div></div><div class="card"><div class="sub">미수령 전리품</div><div class="big">${pending}</div></div><div class="card"><div class="sub">다음 영입 후보</div><div class="big" id="candidateTimer">-</div></div></section><section class="panel"><div class="title"><h3>현재 원정</h3><button class="btn gold" data-go="hunt">사냥터</button></div>${active.length?active.map(e=>{const m=S.monsters.find(x=>x.id===e.monster_id),site=S.sites.find(x=>x.id===e.site_id);return `<div class="card" style="margin-top:7px"><b>${m.name} → ${site.name}</b><div class="sub">서버 전투 ${fmt(e.battle_count)}회 · 처치 ${fmt(e.kills)} · 전리품 ${lootCount(e)}개</div></div>`}).join(''):'<div class="empty">현재 파견된 몬스터가 없습니다.</div>'}</section>`}
function monsters(){return `<section class="panel"><div class="title"><div><h2>몬스터</h2><div class="sub">슬라임 · 고블린 · 트롤을 영입하고 성장시킵니다.</div></div><button class="btn gold" data-action="candidates">영입 후보 ${S.candidates.length}</button></div></section>${S.monsters.map(monsterCard).join('')}`}
function hunt(){return `<section class="panel"><div class="title"><div><h2>인간 지역 사냥</h2><div class="sub">사냥터를 눌러 파견할 몬스터를 고릅니다. 경험치와 레벨은 서버에서 계속 반영됩니다.</div></div></div></section>${S.sites.map(site=>{const ex=expeditionAt(site);return `<section class="card hunt-card" style="${!site.unlocked?'opacity:.45':''}"><div class="title"><div><b>${site.name}</b><div class="sub">${site.description}</div></div><span class="chip ${site.unlocked?(ex.length?'on':''):'lock'}">${site.unlocked?(ex.length?`${ex.length}마리 사냥 중`:'개방'):'잠김'}</span></div><div class="sub" style="margin-top:5px">권장 전투력 ${site.recommended_power} · 적: ${site.enemy_names.join(', ')}</div>${ex.map(e=>{const m=S.monsters.find(x=>x.id===e.monster_id);return `<div class="battle"><canvas width="220" height="120" data-battle="${e.id}"></canvas><div class="title"><div><b>${m.name}</b><div class="sub">전투 ${fmt(e.battle_count)} · 처치 ${fmt(e.kills)} · 미수령 ${lootCount(e)}개</div></div><div><button class="btn blue" data-action="watch" data-id="${e.id}">관전</button> <button class="btn red" data-action="recall" data-id="${e.id}">복귀</button></div></div></div>`}).join('')}<div style="margin-top:7px"><button class="btn gold" data-action="deploy-open" data-id="${site.id}" ${site.unlocked?'':'disabled'}>몬스터 파견</button></div></section>`}).join('')}`}
function loot(){const total=S.expeditions.reduce((a,e)=>a+lootCount(e),0);return `<section class="panel"><div class="title"><div><h2>전리품 보관함</h2><div class="sub">사냥 중 획득한 아이템은 서버 전리품 상자에 쌓이고, 수령할 때 창고로 이동합니다.</div></div><button class="btn gold" data-action="collect-all" ${total?'':'disabled'}>전체 일괄 수령</button></div></section>${S.expeditions.filter(e=>lootCount(e)>0).map(e=>{const m=S.monsters.find(x=>x.id===e.monster_id),site=S.sites.find(x=>x.id===e.site_id);return `<section class="card"><div class="title"><div><b>${site.name} · ${m.name}</b><div class="sub">미수령 ${lootCount(e)}개</div></div><button class="btn" data-action="collect-one" data-id="${e.id}">수령</button></div><div class="loot" style="margin-top:7px">${Object.entries(e.pending_loot||{}).map(([k,v])=>`<div><b>${k}</b><div class="sub">${v}개</div></div>`).join('')}</div></section>`}).join('')}${total?'':'<div class="panel empty">아직 쌓인 전리품이 없습니다.</div>'}<section class="panel"><div class="title"><h3>수령한 창고</h3></div><div class="loot" style="margin-top:7px">${S.inventory.map(x=>`<div><b>${x.item_id}</b><div class="sub">${fmt(x.qty)}개</div></div>`).join('')||'<div class="sub">비어 있음</div>'}</div></section>`}
function facility(){const p=S.player,cap=1+(p.quarters_level-1)*2,costQ=Math.floor(220*Math.pow(1.8,p.quarters_level-1)),costT=Math.floor(260*Math.pow(1.85,p.tavern_level-1));return `<section class="panel"><h2 style="margin:0 0 8px">소굴 시설</h2><div class="grid"><div class="card"><b>숙소 Lv.${p.quarters_level}</b><div class="sub">몬스터 수용 ${S.monsters.length}/${cap}</div><button class="btn gold" style="margin-top:8px" data-action="upgrade" data-id="quarters">${fmt(costQ)}G 확장</button></div><div class="card"><b>영입소 Lv.${p.tavern_level}</b><div class="sub">후보는 기본 4시간마다 도착</div><button class="btn gold" style="margin-top:8px" data-action="upgrade" data-id="tavern">${fmt(costT)}G 강화</button></div></div></section>`}

function render(){if(!S)return;$('#gold').textContent=fmt(S.player.gold);$('#fame').textContent=fmt(S.player.fame);$('#accountName').textContent=S.account?.username||'PLAYER';$('#serverState').textContent='서버 동기화 · '+new Date(S.serverNow).toLocaleTimeString('ko-KR');$('#serverState').className='server';$('#view').innerHTML=screen==='home'?home():screen==='monsters'?monsters():screen==='hunt'?hunt():screen==='loot'?loot():facility();document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===screen));paintCanvases();updateCandidateTimer()}
function paintCanvases(){requestAnimationFrame(()=>{document.querySelectorAll('canvas[data-mid]').forEach(c=>{const m=S?.monsters.find(x=>x.id===c.dataset.mid);if(m){const g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);drawMonster(c,m,28,38)}});document.querySelectorAll('canvas[data-battle]').forEach(c=>{const e=S?.expeditions.find(x=>x.id===c.dataset.battle);if(e)battleCanvas(c,e)})})}
function updateCandidateTimer(){const e=$('#candidateTimer');if(!e||!S?.player?.next_candidate_at)return;const d=Math.max(0,new Date(S.player.next_candidate_at).getTime()-Date.now());if(!d){e.textContent=S.candidates.length?'도착':'곧 도착';return}const h=Math.floor(d/3600000),m=Math.floor((d%3600000)/60000),s=Math.floor((d%60000)/1000);e.textContent=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function modal(html){const m=$('#modal');m.innerHTML=`<div class="sheet">${html}</div>`;m.classList.remove('hidden')}
function close(){const m=$('#modal');m.classList.add('hidden');m.innerHTML=''}
function candidates(){modal(`<div class="title"><h2>영입 후보</h2><button class="btn" data-action="close">닫기</button></div><div class="sub">후보는 서버 시간 기준 4시간마다 찾아옵니다.</div>${S.candidates.map(c=>{const cost=90+Math.floor(c.talent*1.7);return `<div class="card candidate" style="margin-top:7px"><div><b>${c.name} · ${fam(c.family)}</b><div class="sub">재능 ${c.talent} · ${c.trait} · 기본 전투력 ${c.power_base}</div></div><div><button class="btn gold" data-action="hire" data-id="${c.id}">${cost}G 영입</button> <button class="btn" data-action="reject" data-id="${c.id}">거절</button></div></div>`}).join('')||'<div class="empty">현재 후보가 없습니다.</div>'}`)}
function deployOpen(siteId){const site=S.sites.find(x=>x.id===siteId);modal(`<div class="title"><h2>${site.name} 파견</h2><button class="btn" data-action="close">닫기</button></div><div class="sub">몬스터를 선택하면 서버에서 즉시 사냥이 시작됩니다.</div>${S.monsters.map(m=>`<div class="card candidate" style="margin-top:7px"><div><b>${m.name} · Lv.${m.level} ${fam(m.family)}</b><div class="sub">전투력 ${fmt(power(m))}${activeOf(m.id)?' · 현재 다른 지역 사냥 중':''}</div></div><button class="btn gold" data-action="deploy" data-site="${siteId}" data-id="${m.id}">파견</button></div>`).join('')}`)}
function watch(id){const e=S.expeditions.find(x=>x.id===id),m=S.monsters.find(x=>x.id===e.monster_id),site=S.sites.find(x=>x.id===e.site_id);modal(`<div class="title"><div><h2>${site.name}</h2><div class="sub">${m.name} 서버 자동전투 관전</div></div><button class="btn" data-action="close">닫기</button></div><div class="battle"><canvas id="watchCanvas" width="320" height="190"></canvas><div class="log">${(e.battle_log||[]).slice(0,6).map(x=>`${new Date(x.t).toLocaleTimeString('ko-KR')} · ${x.enemy} · ${x.result==='win'?'처치':'패배'}`).join('<br>')||'전투 시작 대기 중...'}</div></div>`);battleCanvas($('#watchCanvas'),e)}
async function refresh(){if(busy||!session||!S)return;try{await api('state');render()}catch(e){if(e.message==='unauthorized'){await sb.auth.signOut();showAuth()}else{$('#serverState').textContent='서버 재연결 중';$('#serverState').className='danger'}}}

function errorKo(code){return {username_format:'아이디는 3~20자의 영문, 숫자, 밑줄(_)만 사용할 수 있습니다.',password_format:'비밀번호는 8~72자로 입력해 주세요.',username_taken:'이미 사용 중인 아이디입니다.',invalid_credentials:'아이디 또는 비밀번호가 맞지 않습니다.',unauthorized:'로그인이 만료되었습니다.',quarters_full:'숙소가 가득 찼습니다.',gold_short:'골드가 부족합니다.',locked:'아직 갈 수 없는 지역입니다.',candidate_missing:'영입 후보가 사라졌습니다.'}[code]||code}

document.querySelectorAll('[data-auth-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));const signup=b.dataset.authTab==='signup';$('#loginForm').classList.toggle('hidden',signup);$('#signupForm').classList.toggle('hidden',!signup);authMsg('')}));
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;authMsg('로그인 중...');try{const u=$('#loginId').value.trim(),p=$('#loginPw').value;const {data,error}=await sb.auth.signInWithPassword({email:loginEmail(u),password:p});if(error)throw new Error('invalid_credentials');session=data.session;authMsg('');await enterGame()}catch(err){authMsg(errorKo(err.message))}finally{busy=false}});
$('#signupForm').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const u=$('#signupId').value.trim(),p=$('#signupPw').value,p2=$('#signupPw2').value;if(p!==p2){authMsg('비밀번호 확인이 일치하지 않습니다.');return}busy=true;authMsg('계정을 생성 중...');try{await registerAccount(u,p);const {data,error}=await sb.auth.signInWithPassword({email:loginEmail(u),password:p});if(error)throw new Error('invalid_credentials');session=data.session;authMsg('계정 생성 완료.',true);await enterGame()}catch(err){authMsg(errorKo(err.message))}finally{busy=false}});

document.addEventListener('click',async e=>{const n=e.target.closest('[data-screen]');if(n){screen=n.dataset.screen;close();render();return}const go=e.target.closest('[data-go]');if(go){screen=go.dataset.go;render();return}const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='logout'){if(busy)return;busy=true;try{await sb.auth.signOut();showAuth()}finally{busy=false}return}try{busy=true;if(a==='close')close();else if(a==='candidates')candidates();else if(a==='deploy-open')deployOpen(b.dataset.id);else if(a==='watch')watch(b.dataset.id);else if(a==='deploy'){await api('deploy',{monsterId:b.dataset.id,siteId:b.dataset.site});close();toast('사냥을 시작했습니다.');render()}else if(a==='recall'){await api('recall',{expeditionId:b.dataset.id});toast('몬스터를 복귀시켰습니다.');render()}else if(a==='collect-all'){await api('collect');toast('전리품을 일괄 수령했습니다.');render()}else if(a==='collect-one'){await api('collect',{expeditionId:b.dataset.id});toast('전리품을 수령했습니다.');render()}else if(a==='hire'){await api('hire',{candidateId:b.dataset.id});close();toast('몬스터를 영입했습니다.');render()}else if(a==='reject'){await api('reject',{candidateId:b.dataset.id});close();toast('후보를 돌려보냈습니다.');render()}else if(a==='upgrade'){await api('upgrade',{facility:b.dataset.id});toast('시설을 확장했습니다.');render()}}catch(err){toast(errorKo(err.message)||'처리에 실패했습니다.')}finally{busy=false}});

sb.auth.onAuthStateChange((_event,newSession)=>{session=newSession});
setInterval(updateCandidateTimer,1000);
setInterval(refresh,5000);
setInterval(()=>{if(!S)return;document.querySelectorAll('canvas[data-battle]').forEach(c=>{const e=S.expeditions.find(x=>x.id===c.dataset.battle);if(e)battleCanvas(c,e)});const w=$('#watchCanvas');if(w&&!$('#modal').classList.contains('hidden')){const id=S.expeditions.find(e=>e.active)?.id;if(id){const ex=S.expeditions.find(e=>e.id===id);if(ex)battleCanvas(w,ex)}}},300);

(async()=>{try{const s=await currentSession();if(s)await enterGame();else showAuth()}catch(e){showAuth();authMsg('초기 연결에 실패했습니다.')}})();