const SB_URL='https://xtvhisddjtfnsumprgpm.supabase.co';
const PUB='sb_publishable_pYdQeWXJJjNHGwchtshJGQ_ybwDsQ5O';
const API=SB_URL+'/functions/v1/dungeon-idel-api';
const sb=window.supabase.createClient(SB_URL,PUB,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});

let screen='home',S=null,busy=false,session=null,watchingExpeditionId=null;
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>Number(n||0).toLocaleString('ko-KR');
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const fam=k=>({slime:'슬라임',goblin:'고블린',troll:'트롤'}[k]||k);
const siteCode=id=>({mountain_village:'OP-001',farm_road:'OP-014',border_outpost:'OP-031'}[id]||'OP-???');
const siteShort=id=>({mountain_village:'산촌',farm_road:'농로',border_outpost:'국경'}[id]||'미확인');
const roleOf=m=>m.family==='slime'?'완충 요원':m.family==='goblin'?'기습 요원':'중장 요원';
const power=m=>Math.floor(Number(m.power_base||0)+(Number(m.level||1)-1)*12+Math.max(0,Number(m.talent||80)-80)*1.2);
const activeOf=mid=>(S?.expeditions||[]).find(e=>e.active&&e.monster_id===mid);
const activeAt=sid=>(S?.expeditions||[]).filter(e=>e.active&&e.site_id===sid);
const lootCount=e=>Object.values(e?.pending_loot||{}).reduce((a,b)=>a+Number(b||0),0);
const totalPending=()=>S?(S.expeditions||[]).reduce((a,e)=>a+lootCount(e),0):0;
const capacity=()=>1+(Math.max(1,Number(S?.player?.quarters_level||1))-1)*2;
const nextQuarterCost=()=>Math.floor(220*Math.pow(1.8,Math.max(1,Number(S?.player?.quarters_level||1))-1));
const nextTavernCost=()=>Math.floor(260*Math.pow(1.85,Math.max(1,Number(S?.player?.tavern_level||1))-1));
const validKoreanId=u=>/^[가-힣]{2,12}$/.test(String(u||'').normalize('NFC'));
const validPin=p=>/^\d{4}$/.test(String(p||''));
const monsterAsset=f=>`monster-${f==='goblin'?'goblin':f==='troll'?'troll':'slime'}`;
const enemyAsset=n=>{const x=String(n||'');if(/나무꾼|농부|짐꾼/.test(x))return 'human-lumberjack';if(/사냥꾼|석궁|호위/.test(x))return 'human-hunter';if(/대장|기사|경비|병사/.test(x))return 'human-captain';return 'human-youth'};
const itemAsset=n=>{const x=String(n||'');if(/동전/.test(x))return 'coin';if(/천/.test(x))return 'cloth';if(/몽둥이/.test(x))return 'club';if(/주머니/.test(x))return 'pouch';if(/가죽/.test(x))return 'leather';if(/낫/.test(x))return 'sickle';if(/철/.test(x))return 'iron';if(/검/.test(x))return 'sword';return 'crate'};
const charSvg=(id,cls='')=>`<svg class="pixel-char ${cls}" viewBox="0 0 64 64" aria-hidden="true"><use href="assets/characters.svg#${id}"></use></svg>`;
const itemSvg=(id,cls='')=>`<svg class="pixel-item ${cls}" viewBox="0 0 48 48" aria-hidden="true"><use href="assets/items.svg#${id}"></use></svg>`;
const buzz=()=>{try{navigator.vibrate?.(12)}catch(_){}};

function toast(text){buzz();const e=$('#toast');if(!e)return;e.textContent=text;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1700)}
function authMsg(text='',ok=false){const e=$('#authMsg');if(!e)return;e.textContent=text;e.classList.toggle('ok',ok)}
function errorKo(code){return ({username_format:'사원명은 한글 2~12글자로 입력해 주세요.',password_format:'보안 PIN은 숫자 4자리입니다.',username_taken:'이미 등록된 사원명입니다.',invalid_credentials:'사원명 또는 PIN이 맞지 않습니다.',unauthorized:'로그인이 만료되었습니다.',quarters_full:'숙소 정원이 가득 찼습니다.',gold_short:'금고 잔액이 부족합니다.',locked:'아직 계약 권한이 없는 지역입니다.',candidate_missing:'영입 후보가 이미 떠났습니다.',invalid_target:'작전 대상을 확인할 수 없습니다.',server_error:'서버 처리 중 오류가 발생했습니다.'}[code]||code||'처리에 실패했습니다.')}

async function currentSession(){const {data,error}=await sb.auth.getSession();if(error)throw error;session=data.session;return session}
async function api(action,payload={}){const s=await currentSession();if(!s)throw new Error('unauthorized');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUB,'Authorization':'Bearer '+s.access_token},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({error:'bad_response'}));if(!r.ok)throw new Error(d.error||'server_error');if(d.state)S=d.state;return d}
async function registerAccount(username,password){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUB},body:JSON.stringify({action:'register',username,password})});const d=await r.json().catch(()=>({error:'bad_response'}));if(!r.ok)throw new Error(d.error||'register_failed');return d}
async function loginAccount(username,password){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUB},body:JSON.stringify({action:'login',username,password})});const d=await r.json().catch(()=>({error:'bad_response'}));if(!r.ok)throw new Error(d.error||'invalid_credentials');return d}
async function applySession(authSession){if(!authSession?.access_token||!authSession?.refresh_token)throw new Error('invalid_credentials');const {data,error}=await sb.auth.setSession({access_token:authSession.access_token,refresh_token:authSession.refresh_token});if(error||!data.session)throw new Error('invalid_credentials');session=data.session}

function closeModal(){const m=$('#modal');if(!m)return;m.classList.add('hidden');m.innerHTML='';watchingExpeditionId=null}
function modal(html,extra=''){const m=$('#modal');m.innerHTML=`<div class="sheet ${extra}">${html}</div>`;m.classList.remove('hidden')}
function showAuth(){closeModal();S=null;session=null;$('#app').classList.add('hidden');$('#authGate').classList.remove('hidden');authMsg('')}
async function enterGame(){const s=await currentSession();if(!s){showAuth();return}$('#authGate').classList.add('hidden');$('#app').classList.remove('hidden');try{await api('state');render()}catch(e){if(e.message==='unauthorized'){await sb.auth.signOut();showAuth()}else{toast('서버 상태를 불러오지 못했습니다.')}}}

function companyRank(){const fame=Number(S?.player?.fame||0);if(fame>=3000)return ['재앙급 법인','S'];if(fame>=1500)return ['대형 박멸사','A'];if(fame>=600)return ['전문 박멸사','B'];if(fame>=150)return ['지역 업체','C'];return ['신생 용역사','D']}
function candidateText(){if(!S?.player?.next_candidate_at)return '-';const d=Math.max(0,new Date(S.player.next_candidate_at).getTime()-Date.now());if(!d)return S.candidates?.length?'면접 대기':'곧 도착';const h=Math.floor(d/3600000),m=Math.floor((d%3600000)/60000);return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function briefText(){const active=(S?.expeditions||[]).filter(e=>e.active).length,pending=totalPending();if(pending)return `화물 ${pending}개 수령 대기`;if(active)return `작전 ${active}건 진행 중`;if((S?.candidates||[]).length)return `지원자 ${(S.candidates||[]).length}명 대기`;return `다음 지원자 ${candidateText()}`}

function drawMonster(c,m,x=32,y=40,scale=1,phase=0){if(!c||!m)return;const g=c.getContext('2d');g.save();g.clearRect(0,0,c.width,c.height);g.imageSmoothingEnabled=false;g.translate(x,y+Math.sin(phase)*1.5);g.scale(scale,scale);const body=m.family==='slime'?'#73b77b':m.family==='goblin'?'#9eb25e':'#7e9071';const dark=m.family==='slime'?'#3d6c49':m.family==='goblin'?'#586733':'#465446';g.fillStyle='#0c0e0c';g.fillRect(-14,16,28,5);if(m.family==='slime'){g.fillStyle=dark;g.fillRect(-12,-2,24,20);g.fillRect(-8,-9,16,8);g.fillRect(-15,7,4,8);g.fillRect(11,7,4,8);g.fillStyle=body;g.fillRect(-10,-4,20,18);g.fillRect(-6,-10,12,7)}else if(m.family==='goblin'){g.fillStyle=body;g.fillRect(-10,-7,20,22);g.fillRect(-15,-5,6,7);g.fillRect(9,-5,6,7);g.fillStyle=dark;g.fillRect(-7,15,5,8);g.fillRect(3,15,5,8);g.fillStyle='#6e4c2d';g.fillRect(12,2,5,22);g.fillRect(8,2,12,4)}else{g.fillStyle=body;g.fillRect(-13,-9,26,25);g.fillRect(-18,-3,6,18);g.fillRect(12,-3,6,18);g.fillStyle=dark;g.fillRect(-9,16,7,9);g.fillRect(3,16,7,9);g.fillStyle='#5c4531';g.fillRect(-6,-15,12,7)}g.fillStyle='#e5dfc4';g.fillRect(-6,-3,4,4);g.fillRect(3,-3,4,4);g.fillStyle='#161816';g.fillRect(-5,-2,2,2);g.fillRect(4,-2,2,2);g.fillStyle='#b46d38';g.fillRect(-5,7,10,3);g.restore()}
function drawEnemy(g,x,y,phase){g.save();g.translate(x,y+Math.sin(phase+.8)*1.2);g.fillStyle='#1a1714';g.fillRect(-11,14,22,4);g.fillStyle='#d1b08d';g.fillRect(-7,-9,14,12);g.fillStyle='#725642';g.fillRect(-9,-14,18,6);g.fillStyle='#6c7480';g.fillRect(-10,3,20,16);g.fillStyle='#beb7a6';g.fillRect(7,1,4,22);g.fillStyle='#d5d0c4';g.fillRect(4,-3,10,4);g.restore()}
function battleCanvas(canvas,e){if(!canvas||!e||!S)return;const m=S.monsters.find(x=>x.id===e.monster_id),site=S.sites.find(x=>x.id===e.site_id);if(!m||!site)return;const g=canvas.getContext('2d'),w=canvas.width,h=canvas.height,t=Date.now()/180;g.clearRect(0,0,w,h);g.imageSmoothingEnabled=false;const cycle=(t%16);const attacking=cycle>5&&cycle<9;const mx=76+(attacking?Math.min(22,(cycle-5)*8):0),ex=w-82-(attacking?0:Math.max(0,Math.sin(t*.7)*3));drawMonster(canvas,m,mx,h-58,1.3,t*.7);drawEnemy(g,ex,h-50,t*.8);if(attacking){g.fillStyle='#f0b65c';g.fillRect(mx+34,h-80,26,5);g.fillRect(mx+49,h-89,5,20);if(cycle>7){g.fillStyle='#d75d52';g.fillRect(ex-18,h-88,8,8);g.fillRect(ex+12,h-96,6,6)}}g.fillStyle='#0009';g.fillRect(8,8,130,18);g.fillStyle='#e8ece6';g.font='10px monospace';g.fillText(`${m.name} · Lv.${m.level}`,14,20);g.fillStyle='#0009';g.fillRect(w-150,8,142,18);g.fillStyle='#e8ece6';g.fillText((e.battle_state?.enemy||site.enemy_names?.[0]||'용사'),w-143,20)}

function hq(){const [rank,grade]=companyRank(),active=(S.expeditions||[]).filter(e=>e.active),pending=totalPending(),cap=capacity(),inv=(S.inventory||[]).reduce((a,x)=>a+Number(x.qty||0),0);return `
<section class="office-banner"><div><span class="office-eyebrow">HERO EXTERMINATION INC.</span><h2>${esc(S.account?.username||'사장')} 대표 본부</h2><p>${rank} · ${grade}등급</p></div><div class="office-badge"><b>${active.length}</b><small>현장</small></div></section>
<section class="facility-stack">
  <button class="facility-row dorm" data-action="dorm"><img src="assets/icon-dorm.svg" alt=""><span class="facility-copy"><b>숙소</b><small>${S.monsters.length}/${cap} 몬스터</small></span><span class="facility-side"><em>Lv.${S.player.quarters_level}</em><i>›</i></span></button>
  <button class="facility-row recruit" data-action="candidates"><img src="assets/icon-recruit.svg" alt=""><span class="facility-copy"><b>영입소</b><small>${(S.candidates||[]).length?`${(S.candidates||[]).length}명 면접 대기`:`다음 지원 ${candidateText()}`}</small></span><span class="facility-side">${(S.candidates||[]).length?'<em class="new">NEW</em>':'<em>대기</em>'}<i>›</i></span></button>
  <button class="facility-row storage" data-go="loot"><img src="assets/icon-storage.svg" alt=""><span class="facility-copy"><b>전리품 창고</b><small>${pending}개 회수 대기 · 보관 ${inv}개</small></span><span class="facility-side"><em>${pending?'확인':'정상'}</em><i>›</i></span></button>
  <button class="facility-row ops" data-go="hunt"><img src="assets/icon-ops.svg" alt=""><span class="facility-copy"><b>박멸 작전실</b><small>${active.length?`${active.length}건 진행 중`:'대기 중'}</small></span><span class="facility-side"><em>${active.length?'LIVE':'READY'}</em><i>›</i></span></button>
</section>
${active.length?`<section class="home-live"><header><b>진행 중인 작전</b><small>${active.length}건</small></header>${active.slice(0,3).map(e=>{const m=S.monsters.find(x=>x.id===e.monster_id),site=S.sites.find(x=>x.id===e.site_id);return `<button data-action="watch" data-id="${e.id}"><span class="live-pin"></span><span><b>${esc(site?.name||'작전')}</b><small>${esc(m?.name||'몬스터')} · 처치 ${fmt(e.kills)} · 화물 ${lootCount(e)}</small></span><i>관전</i></button>`}).join('')}</section>`:''}`}

function dormModal(){const cap=capacity();modal(`<div class="sheet-head lodge-head"><div><div class="section-kicker">MONSTER QUARTERS</div><h2>숙소 인원 관리</h2><p>${S.monsters.length}/${cap}명 입실 · 숙소 Lv.${S.player.quarters_level}</p></div><button class="close-btn" data-action="close">×</button></div><div class="lodge-list">${S.monsters.map(m=>{const e=activeOf(m.id);return `<button class="lodge-row" data-action="employee" data-id="${m.id}"><span class="lodge-avatar">${charSvg(monsterAsset(m.family),'lodge-sprite')}</span><span class="lodge-info"><b>${esc(m.name)}</b><small>${fam(m.family)} · ${esc(m.trait||'무특성')}</small><em class="${e?'field':''}">${e?'현장 출동':'숙소 대기'}</em></span><span class="lodge-stats"><i><small>LV</small><b>${m.level}</b></i><i><small>전투</small><b>${fmt(power(m))}</b></i><i><small>재능</small><b>${fmt(m.talent)}</b></i></span></button>`}).join('')}</div><div class="lodge-footer"><span><small>다음 정원</small><b>${cap} → ${cap+2}명</b></span><button class="primary-btn" data-action="upgrade" data-id="quarters">숙소 확장 · ${fmt(nextQuarterCost())}G</button></div>`,`lodge-sheet`)}

function monsters(){return `
<div class="page-head"><div><span>MONSTER ROSTER</span><h2>몬스터 리스트</h2></div><button class="primary-btn" data-action="candidates">영입 ${(S.candidates||[]).length}</button></div>
<section class="personnel-list">${S.monsters.map(m=>{const e=activeOf(m.id);return `<button class="personnel-row ${e?'deployed':''}" data-action="employee" data-id="${m.id}"><span class="personnel-avatar">${charSvg(monsterAsset(m.family),'employee-sprite')}</span><span class="personnel-info"><b>${esc(m.name)}</b><small>${fam(m.family)} · ${esc(m.trait||'무특성')}</small><em>${e?'현장 출동':'본부 대기'}</em></span><span class="personnel-power"><small>전투력</small><b>${fmt(power(m))}</b><i>LV.${m.level}</i></span></button>`}).join('')}</section>`}

function hunt(){const active=(S.expeditions||[]).filter(e=>e.active);return `
<div class="compact-head"><div><b>박멸 작전</b><small>${active.length}건 진행</small></div></div>
<section class="mission-list compact-missions">${S.sites.map(site=>{const ex=activeAt(site.id),unlocked=!!site.unlocked,pending=ex.reduce((a,e)=>a+lootCount(e),0),battle=ex.reduce((a,e)=>a+Number(e.battle_count||0),0),pct=ex.length?Math.min(94,18+(battle%78)):0;return `<article class="mission-card compact-mission ${unlocked?'':'locked'}" data-action="mission" data-id="${site.id}" data-site="${site.id}"><div class="mission-art"></div><div class="mission-wash"></div><div class="mission-file"><header><div><div class="mission-code">${siteCode(site.id)}</div><div class="mission-title">${esc(site.name)}</div></div><span class="risk">권장 ${fmt(site.recommended_power)}</span></header><div class="mission-middle"><div class="squad">${ex.length?ex.slice(0,3).map(e=>{const mm=S.monsters.find(x=>x.id===e.monster_id);return `<span class="party-avatar">${mm?charSvg(monsterAsset(mm.family),'party-sprite'):''}</span>`}).join(''):'<span class="empty-slot">+</span>'}</div></div><footer class="mission-foot"><div><div class="op-state">${ex.length?`교전 ${battle} · 화물 ${pending}`:(unlocked?'배치 가능':'잠김')}</div><div class="opbar"><i style="width:${pct}%"></i></div></div><div class="mission-cta"><b>${unlocked?(ex.length?'현장':'배치'):'잠김'}</b></div></footer></div></article>`}).join('')}</section>`}


function loot(){const groups=(S.expeditions||[]).filter(e=>lootCount(e)>0),total=totalPending();return `
<div class="compact-head"><div><b>전리품 창고</b><small>${total}개 수령 대기</small></div><button class="primary-btn" data-action="collect-all" ${total?'':'disabled'}>전체 수령</button></div>
${groups.length?groups.map(e=>{const m=S.monsters.find(x=>x.id===e.monster_id),site=S.sites.find(x=>x.id===e.site_id);return `<section class="warehouse-group compact-warehouse"><header><span><b>${esc(site?.name||'현장')}</b><small>${esc(m?.name||'몬스터')} · ${lootCount(e)}개</small></span><button class="soft-btn" data-action="collect-one" data-id="${e.id}">수령</button></header><div class="shelf">${Object.entries(e.pending_loot||{}).map(([name,qty])=>`<div class="item-bin compact-item"><div class="item-art">${itemSvg(itemAsset(name))}</div><b>${esc(name)}</b><strong>${fmt(qty)}</strong></div>`).join('')}</div></section>`}).join(''):`<div class="empty-state warehouse-empty"><div>${itemSvg('crate')}</div><b>대기 화물 없음</b></div>`}
<section class="inventory-card"><div class="compact-head inner"><b>보관 재고</b><small>${(S.inventory||[]).length}종</small></div><div class="inventory-grid">${(S.inventory||[]).length?S.inventory.map(x=>`<div class="inventory-slot"><div class="item-art small">${itemSvg(itemAsset(x.item_id))}</div><b>${esc(x.item_id)}</b><small>${fmt(x.qty)}</small></div>`).join(''):'<div class="empty-state" style="grid-column:1/-1">비어 있음</div>'}</div></section>`}


function updateChrome(){if(!S)return;const active=(S.expeditions||[]).filter(e=>e.active).length;$('#gold').textContent=fmt(S.player.gold);$('#fame').textContent=fmt(S.player.fame);$('#monsterCount').textContent=fmt(S.monsters.length);$('#activeCount').textContent=fmt(active);$('#pendingCount').textContent=fmt(totalPending());$('#screenTitle').textContent=({home:'본부',monsters:'몬스터',hunt:'작전',loot:'창고'}[screen]||'본부');if($('#briefLine'))$('#briefLine').textContent=briefText();$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===screen))}
function render(){if(!S)return;updateChrome();$('#view').innerHTML=screen==='home'?hq():screen==='monsters'?monsters():screen==='hunt'?hunt():loot();requestAnimationFrame(paintCanvases);updateCandidateTimer()}
function paintCanvases(){syncWatchPanel()}

function updateCandidateTimer(){const e=$('#candidateTimer');if(e)e.textContent=candidateText()}

function candidateModal(){modal(`<div class="sheet-head"><div><div class="section-kicker">RECRUITING</div><h2>영입 대기실</h2><p>4시간마다 새로운 몬스터가 지원합니다.</p></div><button class="close-btn" data-action="close">×</button></div><div class="candidate-list">${(S.candidates||[]).length?S.candidates.map(c=>{const cost=90+Math.floor(c.talent*1.7);return `<div class="candidate-card"><div class="candidate-avatar">${charSvg(monsterAsset(c.family),'candidate-sprite')}</div><div><b>${esc(c.name)} · ${fam(c.family)}</b><small>재능 ${c.talent} · ${esc(c.trait)} · 기본 전투력 ${c.power_base}</small><span class="candidate-fit">${c.talent>=95?'특급 인재':c.talent>=88?'우수 인재':'일반 지원자'}</span></div><div class="actions"><button class="primary-btn" data-action="hire" data-id="${c.id}">${cost}G 채용</button><button class="soft-btn" data-action="reject" data-id="${c.id}">거절</button></div></div>`}).join(''):'<div class="empty-state">현재 대기 중인 지원자가 없습니다.<br>다음 도착까지 ${candidateText()}</div>'}</div>`)}

function employeeModal(id){const m=S.monsters.find(x=>x.id===id);if(!m)return;const e=activeOf(m.id),site=e&&S.sites.find(x=>x.id===e.site_id);modal(`<div class="sheet-head"><div><div class="section-kicker">EMPLOYEE RECORD</div><h2>${esc(m.name)} 인사기록</h2><p>${fam(m.family)} · ${roleOf(m)}</p></div><button class="close-btn" data-action="close">×</button></div><div class="monster-detail"><div class="detail-portrait">${charSvg(monsterAsset(m.family),'detail-sprite')}</div><div class="detail-stats"><div><small>레벨</small><b>LV.${m.level}</b></div><div><small>전투력</small><b>${fmt(power(m))}</b></div><div><small>재능</small><b>${fmt(m.talent)}</b></div><div><small>누적 처치</small><b>${fmt(m.kills)}</b></div></div><div class="detail-note"><b>${esc(m.trait||'무특성')}</b><br>${e?`${esc(site?.name||'현장')}에서 현재 근무 중입니다. 전투와 경험치 획득은 서버에서 계속 처리됩니다.`:'현재 본부 대기 중입니다. 박멸 계약 화면에서 현장에 배치할 수 있습니다.'}</div></div>${e?`<div class="battle-actions"><button class="primary-btn" data-action="watch" data-id="${e.id}">현장 관전</button></div>`:''}`)}

function missionModal(siteId){const site=S.sites.find(x=>x.id===siteId);if(!site)return;if(!site.unlocked){toast('아직 계약 권한이 없습니다.');return}const ex=activeAt(site.id);modal(`<div class="sheet-head"><div><div class="section-kicker">${siteCode(site.id)}</div><h2>${esc(site.name)}</h2><p>권장 전투력 ${fmt(site.recommended_power)} · ${esc(site.description||'인간 활동 지역')}</p></div><button class="close-btn" data-action="close">×</button></div>${ex.length?`<div class="brief-list">${ex.map(e=>{const m=S.monsters.find(x=>x.id===e.monster_id);return `<div class="brief-item mission-live-row"><span class="mini-avatar">${m?charSvg(monsterAsset(m.family)):''}</span><div><b>${esc(m?.name||'몬스터')} 현장 투입 중</b><small>전투 ${fmt(e.battle_count)}회 · 처치 ${fmt(e.kills)} · 화물 ${lootCount(e)}개</small><div class="battle-actions"><button class="primary-btn" data-action="watch" data-id="${e.id}">관전</button><button class="danger-btn" data-action="recall" data-id="${e.id}">복귀</button></div></div></div>`}).join('')}</div><div class="section-title" style="margin-top:12px"><h2 style="font-size:14px">추가 투입</h2><small>대기 직원을 배치할 수 있습니다.</small></div>`:''}<div class="dispatch-list">${S.monsters.map(m=>{const a=activeOf(m.id);return `<div class="dispatch-row"><div class="dispatch-avatar">${charSvg(monsterAsset(m.family),'dispatch-sprite')}</div><div><b>${esc(m.name)} · LV.${m.level}</b><small>전투력 ${fmt(power(m))}${a?' · 다른 현장 근무 중':''}</small></div><button class="primary-btn" data-action="deploy" data-id="${m.id}" data-site="${site.id}">${a?'재배치':'투입'}</button></div>`}).join('')}</div>`)}

function battleUi(siteId){return ({
  mountain_village:{alert:'산골 마을 외곽에서 인간 순찰대가 우리 박멸조를 발견했습니다.',copy:'사람의 발길이 드문 숲길을 따라 마을 외곽에 진입했습니다. 민가 주변의 저항 세력을 제거하고 쓸 만한 물자를 회수합니다.'},
  farm_road:{alert:'농촌 길목에서 무장한 호위대가 이동 경로를 가로막았습니다.',copy:'농지와 창고가 이어진 길목입니다. 행상인과 경비병이 자주 지나가므로 교전이 잦지만, 식량과 장비를 확보하기 좋습니다.'},
  border_outpost:{alert:'변경 초소의 경보종이 울렸습니다. 병사들이 박멸조를 포위하려 합니다.',copy:'왕국 변경의 감시 초소입니다. 병사와 기사가 상주해 위험하지만 철제 장비와 왕국 물자를 노릴 수 있습니다.'}
}[siteId]||{alert:'인간 세력이 우리 박멸조의 움직임을 눈치챘습니다.',copy:'현장 상황을 파악하며 저항 세력을 제거하고 전리품을 회수합니다.'})}
function battleHash(v){let h=0;for(const c of String(v||''))h=(h*31+c.charCodeAt(0))>>>0;return h}
function battleLogHtml(e,m,site){const rows=(e.battle_log||[]).slice(0,10);if(!rows.length)return '<div class="combat-log-empty">첫 교전 기록을 기다리는 중...</div>';return rows.map((x,i)=>{const seed=battleHash(`${x.t}|${x.enemy}|${i}`),dmg=Math.max(7,Math.round(power(m)*(.55+(seed%46)/100))),hurt=Math.max(4,Math.round(Number(site?.recommended_power||40)*(.12+(seed%22)/100))),crit=(seed%5===0),enemy=esc(x.enemy||'용사');if(x.result==='win')return `<div class="combat-log-row"><b class="ally">${esc(m.name)}</b>이(가) <b class="enemy">${enemy}</b>에게 <strong>${fmt(dmg)}</strong> 피해를 줬습니다.${crit?'<em>치명타!</em>':''}</div><div class="combat-log-row system">박멸 성공 · 현장 화물 회수 중</div>`;return `<div class="combat-log-row fail"><b class="enemy">${enemy}</b>의 반격! <b class="ally">${esc(m.name)}</b>이(가) <strong>${fmt(hurt)}</strong> 피해를 입었습니다.</div>`}).join('')}
function watchModal(expId){const e=S.expeditions.find(x=>x.id===expId);if(!e)return;const m=S.monsters.find(x=>x.id===e.monster_id),site=S.sites.find(x=>x.id===e.site_id),enemy=e.battle_state?.enemy||site?.enemy_names?.[0]||'용사',ui=battleUi(e.site_id),seed=battleHash(enemy+e.battle_count),floatDmg=Math.max(7,Math.round(power(m)*(.6+(seed%35)/100)));watchingExpeditionId=expId;modal(`<div class="battle-report-head"><div><h2>${esc(site?.name||'현장')}</h2><small>${siteCode(e.site_id)} · 실시간 박멸 작전</small></div><button class="battle-report-close" data-action="close">×</button></div><div class="battle-report-scene ${e.site_id}"><div class="battle-scene-top"><span class="battle-opcode">${siteCode(e.site_id)}</span><span class="battle-server-badge">SERVER LIVE</span></div><div class="battle-party"><div class="battle-actor monster-actor"><div class="actor-frame">${m?charSvg(monsterAsset(m.family),'battle-sprite'):''}</div><span class="battle-name">${esc(m?.name||'몬스터')}</span><span class="battle-hp"><i></i></span></div><div class="battle-impact"></div><div id="liveDamageFloat" class="battle-dmg-float">-${fmt(floatDmg)}</div><div class="battle-actor enemy-actor"><div id="liveEnemySprite" class="actor-frame">${charSvg(enemyAsset(enemy),'battle-sprite')}</div><span id="liveEnemyName" class="battle-name">${esc(enemy)}</span><span class="battle-hp"><i></i></span></div></div></div><div class="battle-report-body"><div id="liveAlert" class="battle-alert">${esc(ui.alert)}</div><div class="battle-zone-copy"><span>${esc(ui.copy)}</span></div><div class="battle-summary"><div><small>교전</small><b><span id="liveBattleCount">${fmt(e.battle_count)}</span>회</b></div><div><small>박멸</small><b><span id="liveKills">${fmt(e.kills)}</span>명</b></div><div><small>회수 화물</small><b><span id="liveLoot">${lootCount(e)}</span>개</b></div></div><div id="liveLog" class="combat-log">${battleLogHtml(e,m,site)}</div></div><div class="battle-report-actions"><button class="retreat" data-action="recall" data-id="${e.id}">현장 철수</button><button class="close" data-action="close">닫기</button></div>`,'battle-report-sheet');syncWatchPanel()}

function menuModal(){const [rank,grade]=companyRank();modal(`<div class="sheet-head"><div><div class="section-kicker">COMPANY MENU</div><h2>경영 메뉴</h2><p>계정과 서버 상태를 확인합니다.</p></div><button class="close-btn" data-action="close">×</button></div><div class="account-panel"><img src="assets/brand-seal.svg" alt=""><div><b>${esc(S.account?.username||'사장')} 대표</b><small>${rank} · 법인등급 ${grade}<br>서버 세이브 정상 연결</small></div></div><div class="menu-actions"><button data-go="home">본부 현황</button><button data-go="monsters">몬스터 리스트</button><button data-go="hunt">박멸 작전</button><button data-go="loot">전리품 창고</button><button class="logout" data-action="logout">로그아웃</button></div>`,`menu-sheet`)}
function briefModal(){const active=(S.expeditions||[]).filter(e=>e.active);modal(`<div class="sheet-head"><div><div class="section-kicker">CONTROL ROOM BRIEF</div><h2>상황실 브리핑</h2><p>현재 회사 운영에서 바로 확인할 내용입니다.</p></div><button class="close-btn" data-action="close">×</button></div><div class="brief-list"><div class="brief-item"><i></i><div><b>서버 자동전투 정상</b><small>${active.length?`${active.length}개 현장이 서버에서 계속 처리되고 있습니다.`:'현재 가동 중인 현장은 없습니다.'}</small></div></div><div class="brief-item"><i></i><div><b>다음 지원자 ${candidateText()}</b><small>지원자는 기본 4시간 간격으로 인사팀에 도착합니다.</small></div></div><div class="brief-item"><i></i><div><b>회수 대기 화물 ${totalPending()}개</b><small>전리품은 자동으로 창고에 들어오지 않으며 직접 수령해야 합니다.</small></div></div></div>`)}

function syncWatchPanel(){if(!watchingExpeditionId||!S)return;const e=S.expeditions.find(x=>x.id===watchingExpeditionId);if(!e)return;const m=S.monsters.find(x=>x.id===e.monster_id),site=S.sites.find(x=>x.id===e.site_id),enemy=e.battle_state?.enemy||site?.enemy_names?.[0]||'용사',ui=battleUi(e.site_id),seed=battleHash(enemy+e.battle_count),floatDmg=Math.max(7,Math.round(power(m)*(.6+(seed%35)/100)));const bc=$('#liveBattleCount'),k=$('#liveKills'),l=$('#liveLoot'),n=$('#liveEnemyName'),log=$('#liveLog'),holder=$('#liveEnemySprite'),alert=$('#liveAlert'),dmg=$('#liveDamageFloat');if(bc)bc.textContent=fmt(e.battle_count);if(k)k.textContent=fmt(e.kills);if(l)l.textContent=lootCount(e);if(n)n.textContent=enemy;if(alert)alert.textContent=ui.alert;if(dmg)dmg.textContent='-'+fmt(floatDmg);if(holder){const u=holder.querySelector('use');if(u)u.setAttribute('href',`assets/characters.svg#${enemyAsset(enemy)}`)}if(log&&m)log.innerHTML=battleLogHtml(e,m,site)}

async function refresh(){if(busy||!session||!S)return;try{await api('state');render()}catch(e){if(e.message==='unauthorized'){await sb.auth.signOut();showAuth()}else{if($('#briefLine'))$('#briefLine').textContent='서버 재연결 중...'}}}

$$('[data-auth-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));const signup=b.dataset.authTab==='signup';$('#loginForm').classList.toggle('hidden',signup);$('#signupForm').classList.toggle('hidden',!signup);authMsg('')}));
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const u=$('#loginId').value.trim().normalize('NFC'),p=$('#loginPw').value;if(!validKoreanId(u)){authMsg(errorKo('username_format'));return}if(!validPin(p)){authMsg(errorKo('password_format'));return}busy=true;authMsg('본부 연결 중...');try{const d=await loginAccount(u,p);await applySession(d.session);authMsg('');await enterGame()}catch(err){authMsg(errorKo(err.message))}finally{busy=false}});
$('#signupForm').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const u=$('#signupId').value.trim().normalize('NFC'),p=$('#signupPw').value,p2=$('#signupPw2').value;if(!validKoreanId(u)){authMsg(errorKo('username_format'));return}if(!validPin(p)){authMsg(errorKo('password_format'));return}if(p!==p2){authMsg('PIN 확인이 일치하지 않습니다.');return}busy=true;authMsg('사원 등록 중...');try{const d=await registerAccount(u,p);await applySession(d.session);authMsg('등록 완료.',true);await enterGame()}catch(err){authMsg(errorKo(err.message))}finally{busy=false}});

document.addEventListener('click',async e=>{const nav=e.target.closest('[data-screen]');if(nav){screen=nav.dataset.screen;closeModal();render();return}const go=e.target.closest('[data-go]');if(go){screen=go.dataset.go;closeModal();render();return}const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='close'){closeModal();return}if(a==='menu'){menuModal();return}if(a==='brief'){briefModal();return}if(a==='candidates'){candidateModal();return}if(a==='dorm'){dormModal();return}if(a==='employee'){employeeModal(b.dataset.id);return}if(a==='mission'){missionModal(b.dataset.id);return}if(a==='watch'){watchModal(b.dataset.id);return}if(a==='logout'){if(busy)return;busy=true;try{await sb.auth.signOut();showAuth()}finally{busy=false}return}try{busy=true;if(a==='deploy'){await api('deploy',{monsterId:b.dataset.id,siteId:b.dataset.site});closeModal();toast('현장 투입 완료');render()}else if(a==='recall'){await api('recall',{expeditionId:b.dataset.id});closeModal();toast('직원이 본부로 복귀했습니다.');render()}else if(a==='collect-all'){await api('collect');toast('대기 화물을 모두 수령했습니다.');render()}else if(a==='collect-one'){await api('collect',{expeditionId:b.dataset.id});toast('화물을 창고로 옮겼습니다.');render()}else if(a==='hire'){await api('hire',{candidateId:b.dataset.id});closeModal();toast('신규 직원을 채용했습니다.');render()}else if(a==='reject'){await api('reject',{candidateId:b.dataset.id});closeModal();toast('지원자를 돌려보냈습니다.');render()}else if(a==='upgrade'){await api('upgrade',{facility:b.dataset.id});toast('시설 확장이 완료됐습니다.');render()}}catch(err){toast(errorKo(err.message))}finally{busy=false}});

sb.auth.onAuthStateChange((_event,newSession)=>{session=newSession});
setInterval(updateCandidateTimer,1000);
setInterval(refresh,5000);
setInterval(syncWatchPanel,900);

(async()=>{try{const s=await currentSession();if(s)await enterGame();else showAuth()}catch(e){showAuth();authMsg('초기 서버 연결에 실패했습니다.')}})();
