/* Defense scene interpolates movement; hits, rewards and upgrades remain server-owned. */
(()=>{
 let raf=0,previousHp=new Map();
 const defenders=()=>S.monsters.filter(m=>!activeOf(m.id));
 const power=m=>Math.round((8+m.level*3)*(1+(m.evolution_tier||0)*.75)*({C:1,B:1.15,A:1.35,S:1.65}[m.growth_grade]||1));
 const facilities=[['traps','톱니 함정','통로 지점마다 큰 피해',120,'⚒'],['gas','독가스 배관','모든 침입자에게 지속 피해',180,'☁'],['slow','끈적한 바닥','마왕방까지 이동 시간 연장',240,'◷'],['arcane','마력 포탑','선두 용사에게 추가 공격',300,'✦']];
 function scene(){return `<div class="defense-scene" aria-label="용사가 마왕방으로 이동하는 던전 방어 전투"><div class="defense-corridor"></div><div class="defense-entry">용사 입구</div><div class="defense-throne"><span>♛</span><b>마왕방</b></div><div class="defense-trap trap-one">⚙</div><div class="defense-trap trap-two">⚙</div><div id="defenseHeroes"></div><div id="defenseStaff" class="defense-staff"></div><div id="defenseProjectiles"></div><div class="defense-wave-result" aria-live="polite"></div></div>`;}
 function screenHtml(){const d=S.defense||{},team=defenders();return `<section class="defense-heading"><div><small>DUNGEON SECURITY</small><h2>본사 지하를 지켜라</h2><p>대기 직원들이 용사를 저지합니다. 마왕방 도착 전 전원 처치!</p></div><span class="office-rank">${d.stage||1}</span></section><section class="defense-toolbar"><label>반복 단계<select id="defenseStage" aria-label="던전방어 단계">${Array.from({length:d.highest_stage||1},(_,i)=>`<option value="${i+1}" ${i+1===(d.stage||1)?'selected':''}>${i+1}단계</option>`).join('')}</select></label><button class="primary-btn" data-defense-action="boss">${d.boss_auto?'연속 도전 중 · 중단':'보스 연속 도전'}</button></section><p class="defense-boss-rule">보스 승리 → 다음 단계 도전 · 실패 → 도전 OFF, 직전 단계 반복</p>${scene()}<div class="defense-status" role="status"><b id="defenseStatus">${esc(d.last_event?.text||'새 웨이브 준비')}</b><span id="defenseRecord">성공 ${fmt(d.wins)} · 돌파 ${fmt(d.losses)}</span></div><section class="defense-team"><header><b>자동 배치 ${team.length}명</b><span>합산 공격 ${fmt(team.reduce((v,m)=>v+power(m),0))}</span></header><p>탐험에 출정하면 방어에서 빠지고, 복귀하면 다시 합류합니다.</p><div>${team.length?team.map(m=>`<button data-action="employee" data-id="${esc(m.id)}"><span>${OfficeArt.monster(m.family,'form-'+m.form_id)}</span><b>${esc(m.name)}</b><small>${m.growth_grade} · 진화 ${m.evolution_tier||0} · Lv.${m.level}</small><em>공격 ${fmt(power(m))}</em></button>`).join(''):'<p class="idle-empty">모두 탐험 중입니다. 직원을 더 영입하거나 일부를 복귀시키세요.</p>'}</div></section><section class="defense-upgrades"><header><h3>본사 보안 설비</h3><small>골드로 영구 강화 · 최대 Lv.25</small></header>${facilities.map(([id,name,desc,base,icon])=>{const lv=Number(d[id]||0),cost=Math.ceil(base*1.7**lv);return `<article><span>${icon}</span><div><b>${name} <em>Lv.${lv}</em></b><small>${desc}</small></div><button class="soft-btn" data-defense-action="upgrade" data-kind="${id}" ${lv>=25||S.player.gold<cost?'disabled':''}>${lv>=25?'최대':fmt(cost)+'G'}</button></article>`}).join('')}</section><section class="defense-rewards"><b>방어 보상</b><p>경험치는 지급하지 않습니다. 성공한 웨이브는 해당 챕터 적의 전리품을 탐험 확률의 25%로 추첨합니다. 전설은 보스 전용입니다.</p><div data-defense-receipt>${Object.keys(d.last_event?.drops||{}).length?CampaignLoot.receipt(d.last_event.drops,{stored:true}):'<small>전리품은 자동으로 창고에 보관됩니다.</small>'}</div></section>`;}
 function refresh(){if(screen!=='defense'||!document.querySelector('.defense-scene'))return;const d=S.defense||{},w=d.wave||{},team=defenders();
  const status=document.querySelector('#defenseStatus');if(status)status.textContent=d.last_event?.text||'웨이브 준비';const record=document.querySelector('#defenseRecord');if(record)record.textContent=`성공 ${fmt(d.wins)} · 돌파 ${fmt(d.losses)}`;
  const btn=document.querySelector('[data-defense-action="boss"]');if(btn)btn.textContent=d.boss_auto?'연속 도전 중 · 중단':'보스 연속 도전';
  const stageBadge=document.querySelector('.defense-heading .office-rank');if(stageBadge)stageBadge.textContent=d.stage||1;
  for(const [id,, ,base] of facilities){const button=document.querySelector(`[data-defense-action="upgrade"][data-kind="${id}"]`);if(button){const lv=Number(d[id]||0),cost=Math.ceil(base*1.7**lv);button.disabled=lv>=25||S.player.gold<cost;button.textContent=lv>=25?'최대':fmt(cost)+'G';button.closest('article').querySelector('em').textContent='Lv.'+lv;}}
  const stage=document.querySelector('#defenseStage');if(stage){const html=Array.from({length:d.highest_stage||1},(_,i)=>`<option value="${i+1}" ${i+1===(d.stage||1)?'selected':''}>${i+1}단계</option>`).join('');if(stage.innerHTML!==html&&document.activeElement!==stage)stage.innerHTML=html;}
  const staff=document.querySelector('#defenseStaff'),staffKey=team.map(m=>m.id+':'+m.form_id).join();if(staff&&staff.dataset.key!==staffKey){staff.dataset.key=staffKey;staff.style.setProperty('--staff-columns',Math.max(1,team.length<=4?team.length:Math.ceil(team.length/2)));staff.style.setProperty('--staff-count',Math.max(1,team.length));staff.innerHTML=team.map(m=>`<span class="defense-defender" data-defender="${m.id}">${OfficeArt.monster(m.family,'form-'+m.form_id)}</span>`).join('');}
  const heroBox=document.querySelector('#defenseHeroes'),key=JSON.stringify([d.wave_number,w.tick]);
  if(heroBox&&key!==heroBox.dataset.key){const sameWave=heroBox.dataset.wave===String(d.wave_number);heroBox.dataset.key=key;heroBox.dataset.wave=String(d.wave_number);if(!sameWave)previousHp.clear();heroBox.innerHTML=(w.heroes||[]).map(h=>`<div class="defense-hero ${Number(h.hp)<=0?'fallen':''} ${w.boss?'boss':''}" data-hero="${h.id}"><b>${esc(h.name)}</b>${charSvg(enemyAsset(h.name),'defense-hero-sprite')}<i><em style="width:${Math.max(0,h.hp/h.maxHp*100)}%"></em></i></div>`).join('');
   for(const h of w.heroes||[]){const old=previousHp.get(h.id);if(old!=null&&h.hp<old)OfficeArt.animate(heroBox.querySelector(`[data-hero="${h.id}"]`),'office-hit');}previousHp=new Map((w.heroes||[]).map(h=>[h.id,h.hp]));
   if(w.active&&(w.heroes||[]).some(h=>h.hp>0&&h.position>=0))for(const actor of staff.querySelectorAll('.defense-defender')){OfficeArt.animate(actor,'office-strike');const target=(w.heroes||[]).filter(h=>h.hp>0&&h.position>=0).sort((a,b)=>b.position-a.position)[0];if(target&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const box=document.querySelector('.defense-scene'),r=box.getBoundingClientRect(),a=actor.getBoundingClientRect(),x=a.left+a.width/2-r.left,y=a.top+15-r.top,endX=(6+target.position*79)/100*r.width;const bolt=document.createElement('i');bolt.className='defense-bolt';bolt.style.cssText=`left:${x}px;top:${y}px;--bolt-x:${endX-x}px;--bolt-y:${125-y}px`;box.append(bolt);setTimeout(()=>bolt.remove(),450);}}
   const result=document.querySelector('.defense-wave-result');if(result){result.textContent=w.active?'':w.result==='win'?'방어 성공':w.result==='loss'?'용사 돌파 · 보상 없음':'';result.className='defense-wave-result '+(w.result||'');}
  }
  const teamBox=document.querySelector('.defense-team'),teamKey=team.map(m=>[m.id,m.level,m.growth_grade,m.form_id].join(':')).join('|');if(teamBox&&teamBox.dataset.key!==teamKey){const wrap=document.createElement('div');wrap.innerHTML=screenHtml();const fresh=wrap.querySelector('.defense-team');fresh.dataset.key=teamKey;teamBox.replaceWith(fresh);}
  const lootBox=document.querySelector('.defense-rewards');if(lootBox&&Object.keys(d.last_event?.drops||{}).length){const html=CampaignLoot.receipt(d.last_event.drops,{stored:true});let receipt=lootBox.querySelector('[data-defense-receipt]');if(!receipt){receipt=document.createElement('div');receipt.dataset.defenseReceipt='';lootBox.append(receipt);}if(receipt.innerHTML!==html)receipt.innerHTML=html;}
  const sceneBox=document.querySelector('.defense-scene');sceneBox.classList.toggle('has-gas',Number(d.gas)>0);sceneBox.classList.toggle('has-traps',Number(d.traps)>0);
  if(!raf)raf=requestAnimationFrame(frame);
 }
 function frame(){raf=0;if(screen!=='defense'||document.hidden)return;const d=S?.defense,w=d?.wave;if(!w)return;
  const elapsed=Math.min(2,Math.max(0,(Date.now()-new Date(w.at||S.serverNow))/1000));
  for(const h of w.heroes||[]){const el=document.querySelector(`[data-hero="${h.id}"]`);if(el){const drift=w.active&&h.hp>0?elapsed/(60+Math.min(20,d.slow||0)*2):0;el.style.left=`${6+Math.max(-.12,Math.min(1,h.position+drift))*79}%`;}}
  raf=requestAnimationFrame(frame);
 }
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-defense-action]');if(!b||busy)return;e.preventDefault();busy=true;b.disabled=true;try{if(b.dataset.defenseAction==='boss')await api('defense-command',{command:S.defense?.boss_auto?'stop-boss':'boss-auto'});else await api('defense-upgrade',{kind:b.dataset.kind,expectedLevel:Number(S.defense?.[b.dataset.kind]||0)});render();}catch(err){toast(errorKo(err.message));b.disabled=false;}finally{busy=false}});
 document.addEventListener('change',async e=>{if(e.target.id!=='defenseStage'||busy)return;busy=true;try{await api('defense-command',{command:'stage',stage:Number(e.target.value)});render();}catch(err){toast(errorKo(err.message));}finally{busy=false}});
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});window.DefenseUI={screen:screenHtml,refresh,power};
})();
