from pathlib import Path
import re

p=Path('app.js')
s=p.read_text()

s=s.replace("let screen='home',S=null,busy=false,session=null,watchingExpeditionId=null;","let screen='home',S=null,busy=false,session=null,watchingExpeditionId=null,partyPick=[],partySite=null;",1)
s=s.replace("function closeModal(){const m=$('#modal');if(!m)return;m.classList.add('hidden');m.innerHTML='';watchingExpeditionId=null}","function closeModal(){const m=$('#modal');if(!m)return;m.classList.add('hidden');m.innerHTML='';watchingExpeditionId=null;partyPick=[];partySite=null}",1)

stats="""const growthMul=m=>({S:1.21,A:1.13,B:1.06,C:1}[m?.growth_grade||'C']||1);
const monsterStats=m=>{const eq=equippedFor(m.id).map(x=>itemDef(x.item_id)).filter(Boolean),sum=k=>eq.reduce((a,x)=>a+Number(x[k]||0),0),p=m.personality||'침착',tr=m.trait||'',g=growthMul(m),lv=Math.max(1,Number(m.level||1));let st={hp:Math.round(Number(m.hp_base||120)+(lv-1)*9*g+Math.max(0,Number(m.talent||80)-80)*2+sum('hp')),atk:Number(m.atk_base||18)+(lv-1)*2*g+Math.max(0,Number(m.talent||80)-80)*.22+sum('atk'),def:Number(m.def_base||8)+(lv-1)*.8*g+sum('def'),spd:Number(m.spd_base||10)+(lv-1)*.18*g+sum('spd'),crit:Number(m.crit_base||.05)+sum('crit'),evade:Number(m.evade_base||.03)+sum('evade'),human:sum('human_damage')};if(tr==='질긴 가죽')st.def*=1.10;else if(tr==='재빠름'){st.spd*=1.08;st.evade+=.02}if(p==='광전사'){st.atk*=1.15;st.def*=.90;st.crit+=.05}else if(p==='겁쟁이'){st.atk*=.95;st.spd*=1.05;st.evade+=.08}else if(p==='인간혐오'){st.human+=.12}else if(p==='침착'){st.def*=1.10;st.evade+=.02}else if(p==='야행성'&&(kstHour()>=18||kstHour()<6)){st.atk*=1.12;st.spd*=1.12}st.atk=Math.round(st.atk);st.def=Math.round(st.def);st.spd=Math.round(st.spd);st.crit=Math.min(.45,st.crit);st.evade=Math.min(.35,st.evade);return st};"""
s,n=re.subn(r"const monsterStats=.*?;\nconst power=",stats+"\nconst power=",s,count=1,flags=re.S)
if n!=1: raise SystemExit('monsterStats patch failed')

helpers="""const expById=id=>(S?.expeditions||[]).find(e=>e.id===id);
const membersOf=e=>(S?.expeditionMembers||[]).filter(x=>x.expedition_id===e?.id).sort((a,b)=>a.position-b.position);
const partyOf=e=>membersOf(e).map(x=>(S?.monsters||[]).find(m=>m.id===x.monster_id)).filter(Boolean);
const activeOf=mid=>{const row=(S?.expeditionMembers||[]).find(x=>x.monster_id===mid&&expById(x.expedition_id)?.active);return row?expById(row.expedition_id):null};
const activeAt=sid=>(S?.expeditions||[]).filter(e=>e.active&&e.site_id===sid);
const lootCount=e=>Object.values(e?.pending_loot||{}).reduce((a,b)=>a+Number(b||0),0);
const totalPending=()=>S?(S.expeditions||[]).reduce((a,e)=>a+lootCount(e),0):0;
const capacity=()=>1+(Math.max(1,Number(S?.player?.quarters_level||1))-1)*2;
const facilityCost=k=>Number(S?.facilityCosts?.[k]||0);
const nextQuarterCost=()=>facilityCost('quarters');
const nextTavernCost=()=>facilityCost('tavern');
const inventoryQty=id=>Number((S?.inventory||[]).find(x=>x.item_id===id)?.qty||0);
const inventoryUsed=()=>Number((S?.inventory||[]).reduce((a,x)=>a+Number(x.qty||0),0));
const recipeForOutput=id=>(S?.recipes||[]).find(x=>x.output_item===id)||null;
const secText=n=>{n=Math.max(0,Math.round(Number(n||0)));const m=Math.floor(n/60),ss=n%60;return m?`${m}분 ${String(ss).padStart(2,'0')}초`:`${ss}초`};
const leftText=t=>secText(Math.max(0,(new Date(t).getTime()-Date.now())/1000));
const partyLabel=e=>{const p=partyOf(e);return p.length>1?`${p[0]?.name||'몬스터'} 외 ${p.length-1}`:(p[0]?.name||'몬스터')};"""
s,n=re.subn(r"const activeOf=.*?const nextTavernCost=.*?;",helpers,s,count=1,flags=re.S)
if n!=1: raise SystemExit('helpers patch failed')

err="""function errorKo(code){return ({username_format:'사원명은 한글 2~12글자로 입력해 주세요.',password_format:'보안 PIN은 숫자 4자리입니다.',username_taken:'이미 등록된 사원명입니다.',invalid_credentials:'사원명 또는 PIN이 맞지 않습니다.',unauthorized:'로그인이 만료되었습니다.',quarters_full:'숙소 정원이 가득 찼습니다.',gold_short:'금고 잔액이 부족합니다.',locked:'이전 지역 보스를 먼저 처치해야 합니다.',candidate_missing:'영입 후보가 이미 떠났습니다.',invalid_target:'작전 대상을 확인할 수 없습니다.',not_equipment:'장착할 수 없는 물품입니다.',item_missing:'창고에 해당 물품이 없습니다.',storage_full:'창고가 가득 차서 전리품을 수령할 수 없습니다.',party_size:'파티는 1~4마리로 구성해야 합니다.',monster_busy:'이미 다른 작전에 참가 중인 몬스터가 있습니다.',ops_full:'작전실 동시 파견 한도에 도달했습니다.',recipe_missing:'제작법을 찾을 수 없습니다.',workshop_level:'제작소 레벨이 부족합니다.',craft_queue_full:'제작 대기열이 가득 찼습니다.',material_short:'제작 재료가 부족합니다.',not_sellable:'제작품만 상점에 판매할 수 있습니다.',sell_queue_full:'상점이 다른 물품을 판매 중입니다.',max_level:'시설이 현재 최대 레벨입니다.',server_error:'서버 처리 중 오류가 발생했습니다.'}[code]||code||'처리에 실패했습니다.')}"""
s,n=re.subn(r"function errorKo\(code\)\{.*?\}\n\nasync function currentSession",err+"\n\nasync function currentSession",s,count=1,flags=re.S)
if n!=1: raise SystemExit('error patch failed')

hq="""function hq(){const [rank,grade]=companyRank(),active=(S.expeditions||[]).filter(e=>e.active),pending=totalPending(),cap=capacity(),used=inventoryUsed(),crafting=(S.craftJobs||[]).filter(x=>x.status==='running').length,selling=(S.sellJobs||[]).some(x=>x.status==='running');return `
<section class="office-banner"><div><span class="office-eyebrow">HERO EXTERMINATION INC.</span><h2>${esc(S.account?.username||'사장')} 대표 본부</h2><p>${rank} · ${grade}등급</p></div><div class="office-badge"><b>${active.length}</b><small>작전</small></div></section>
<section class="facility-stack">
  <button class="facility-row dorm" data-action="dorm"><img src="assets/icon-dorm.svg" alt=""><span class="facility-copy"><b>숙소</b><small>${S.monsters.length}/${cap} 몬스터</small></span><span class="facility-side"><em>Lv.${S.player.quarters_level}</em><i>›</i></span></button>
  <button class="facility-row recruit" data-action="candidates"><img src="assets/icon-recruit.svg" alt=""><span class="facility-copy"><b>영입소</b><small>4시간마다 ${S.player.tavern_level}명 · 현재 ${(S.candidates||[]).length}명</small></span><span class="facility-side"><em>Lv.${S.player.tavern_level}</em><i>›</i></span></button>
  <button class="facility-row workshop" data-action="workshop"><img src="assets/icon-workshop.svg" alt=""><span class="facility-copy"><b>제작소</b><small>${crafting}/${S.craftCapacity||1} 제작 중</small></span><span class="facility-side"><em>Lv.${S.player.workshop_level||1}</em><i>›</i></span></button>
  <button class="facility-row shop" data-action="shop"><img src="assets/icon-shop.svg" alt=""><span class="facility-copy"><b>상점</b><small>${selling?'판매 진행 중':'제작품 판매 대기'}</small></span><span class="facility-side"><em>${selling?'BUSY':'OPEN'}</em><i>›</i></span></button>
  <button class="facility-row storage" data-go="loot"><img src="assets/icon-storage.svg" alt=""><span class="facility-copy"><b>전리품 창고</b><small>${pending}개 회수 대기 · ${used}/${S.storageCapacity||40}</small></span><span class="facility-side"><em>Lv.${S.player.storage_level||1}</em><i>›</i></span></button>
  <button class="facility-row ops" data-go="hunt"><img src="assets/icon-ops.svg" alt=""><span class="facility-copy"><b>박멸 작전실</b><small>${active.length}/${S.opsCapacity||1}개 파티 출동</small></span><span class="facility-side"><em>Lv.${S.player.ops_level||1}</em><i>›</i></span></button>
</section>
${active.length?`<section class="home-live"><header><b>진행 중인 작전</b><small>${active.length}건</small></header>${active.slice(0,3).map(e=>{const site=S.sites.find(x=>x.id===e.site_id),p=partyOf(e);return `<button data-action="watch" data-id="${e.id}"><span class="live-pin"></span><span><b>${esc(site?.name||'작전')}</b><small>${esc(partyLabel(e))} · ${p.length}인 · 승리 ${fmt(e.kills)} · 화물 ${lootCount(e)}</small></span><i>관전</i></button>`}).join('')}</section>`:''}`}"""
s,n=re.subn(r"function hq\(\).*?(?=\nfunction dormModal)",hq+"\n",s,count=1,flags=re.S)
if n!=1: raise SystemExit('hq patch failed')

dorm="""function dormModal(){const cap=capacity();modal(`<div class="sheet-head lodge-head"><div><div class="section-kicker">MONSTER QUARTERS</div><h2>숙소 인원 관리</h2><p>${S.monsters.length}/${cap}명 입실 · 숙소 Lv.${S.player.quarters_level}</p></div><button class="close-btn" data-action="close">×</button></div><div class="lodge-list">${S.monsters.map(m=>{const e=activeOf(m.id);return `<button class="lodge-row" data-action="employee" data-id="${m.id}"><span class="lodge-avatar">${charSvg(monsterAsset(m.family),'lodge-sprite')}</span><span class="lodge-info"><b>${esc(m.name)}</b><small>${fam(m.family)} · 성장 ${esc(m.growth_grade||'C')} · ${esc(m.trait||'무특성')}</small><em class="${e?'field':''}">${e?'현장 출동':'숙소 대기'}</em></span><span class="lodge-stats"><i><small>LV</small><b>${m.level}</b></i><i><small>전투</small><b>${fmt(power(m))}</b></i><i><small>재능</small><b>${fmt(m.talent)}</b></i></span></button>`}).join('')}</div><div class="lodge-footer"><span><small>다음 정원</small><b>${cap} → ${cap+2}명</b></span><button class="primary-btn" data-action="upgrade" data-id="quarters">숙소 확장 · ${fmt(nextQuarterCost())}G</button></div>`,`lodge-sheet`)}"""
s,n=re.subn(r"function dormModal\(\).*?(?=\nfunction monsters)",dorm+"\n",s,count=1,flags=re.S)
if n!=1: raise SystemExit('dorm patch failed')

hunt="""function hunt(){const active=(S.expeditions||[]).filter(e=>e.active);return `
<div class="compact-head"><div><b>박멸 작전</b><small>${active.length}/${S.opsCapacity||1}개 파티 출동</small></div><button class="soft-btn" data-action="upgrade" data-id="ops">작전실 Lv.${S.player.ops_level||1} · ${fmt(facilityCost('ops'))}G</button></div>
<section class="mission-list compact-missions">${S.sites.map(site=>{const ex=activeAt(site.id),unlocked=!!site.unlocked,pending=ex.reduce((a,e)=>a+lootCount(e),0),wins=Number(site.progress?.normal_wins||0),bossReady=!!site.progress?.boss_ready,bossCleared=!!site.progress?.boss_cleared,pct=bossCleared?100:Math.min(100,wins/500*100),party=ex[0]?partyOf(ex[0]):[];return `<article class="mission-card compact-mission ${unlocked?'':'locked'}" data-action="mission" data-id="${site.id}" data-site="${site.id}"><div class="mission-art"></div><div class="mission-wash"></div><div class="mission-file"><header><div><div class="mission-code">${siteCode(site.id)}</div><div class="mission-title">${esc(site.name)}${bossReady?'<span class="boss-flag">BOSS</span>':bossCleared?'<span class="boss-flag cleared">CLEAR</span>':''}</div></div><span class="risk">권장 ${fmt(site.recommended_power)}</span></header><div class="mission-middle"><div class="squad">${party.length?party.slice(0,4).map(mm=>`<span class="party-avatar">${charSvg(monsterAsset(mm.family),'party-sprite')}</span>`).join(''):'<span class="empty-slot">+</span>'}</div></div><footer class="mission-foot"><div><div class="op-state">${ex.length?`${esc(ex[0]?.phase||'탐색')} · ${party.length}인 · 화물 ${pending}`:(unlocked?(bossReady?'보스 출현':bossCleared?'보스 격파':'파티 배치 가능'):'이전 보스 처치 필요')}</div><div class="stage-progress"><span><i style="width:${pct}%"></i></span><small>${bossCleared?'완료':bossReady?'500/500':`${Math.min(500,wins)}/500`}</small></div></div><div class="mission-cta"><b>${unlocked?(ex.length?'현장':'편성'):'잠김'}</b></div></footer></div></article>`}).join('')}</section>`}"""
s,n=re.subn(r"function hunt\(\).*?(?=\n\nfunction loot)",hunt+"\n",s,count=1,flags=re.S)
if n!=1: raise SystemExit('hunt patch failed')

loot="""function loot(){const groups=(S.expeditions||[]).filter(e=>lootCount(e)>0),total=totalPending(),used=inventoryUsed(),cap=Number(S.storageCapacity||40),pct=Math.min(100,used/cap*100);return `
<div class="compact-head"><div><b>전리품 창고</b><small>보관 ${used}/${cap} · 수령 대기 ${total}</small></div><button class="soft-btn" data-action="upgrade" data-id="storage">창고 Lv.${S.player.storage_level||1} · ${fmt(facilityCost('storage'))}G</button></div>
<div class="storage-meter"><div><i style="width:${pct}%"></i></div><span>${Math.round(pct)}%</span></div>
<div style="display:flex;justify-content:flex-end;margin-bottom:6px"><button class="primary-btn" data-action="collect-all" ${total?'':'disabled'}>전체 수령</button></div>
${groups.length?groups.map(e=>{const site=S.sites.find(x=>x.id===e.site_id);return `<section class="warehouse-group compact-warehouse"><header><span><b>${esc(site?.name||'현장')}</b><small>${esc(partyLabel(e))} · ${lootCount(e)}개 · ${esc(e.phase||'탐색')}</small></span><button class="soft-btn" data-action="collect-one" data-id="${e.id}">수령</button></header><div class="shelf">${Object.entries(e.pending_loot||{}).map(([name,qty])=>`<div class="item-bin compact-item"><div class="item-art">${itemSvg(itemAsset(name))}</div><b>${esc(name)}</b><strong>${fmt(qty)}</strong></div>`).join('')}</div></section>`}).join(''):`<div class="empty-state warehouse-empty"><div>${itemSvg('crate')}</div><b>대기 화물 없음</b></div>`}
<section class="inventory-card"><div class="compact-head inner"><b>보관 재고</b><small>재료 → 제작소 / 장비 → 몬스터</small></div><div class="inventory-grid">${(S.inventory||[]).length?S.inventory.map(x=>{const d=itemDef(x.item_id),r=recipeForOutput(x.item_id);return `<button class="inventory-slot ${d?.slot?'equippable '+rarityClass(d.rarity):r?'crafted':''}" data-action="item" data-id="${esc(x.item_id)}"><div class="item-art small">${itemSvg(itemAsset(x.item_id))}</div><b>${esc(x.item_id)}</b><small>${fmt(x.qty)}${d?.slot?' · '+slotName(d.slot):r?' · 판매품':''}</small></button>`}).join(''):'<div class="empty-state" style="grid-column:1/-1">비어 있음</div>'}</div></section>`}"""
s,n=re.subn(r"function loot\(\).*?(?=\n\nfunction updateChrome)",loot+"\n",s,count=1,flags=re.S)
if n!=1: raise SystemExit('loot patch failed')

workshop_shop="""
function workshopModal(){const lv=Number(S.player.workshop_level||1),running=(S.craftJobs||[]).filter(x=>x.status==='running'),queueFull=running.length>=Number(S.craftCapacity||1);modal(`<div class="sheet-head"><div><div class="section-kicker">WORKSHOP</div><h2>제작소</h2><p>재료를 판매용 제품으로 가공합니다.</p></div><button class="close-btn" data-action="close">×</button></div><div class="facility-upgrade"><span><small>제작소 Lv.${lv}</small><b>동시 제작 ${S.craftCapacity||1}칸 · 레벨별 제작법 해금</b></span><button class="soft-btn" data-action="upgrade" data-id="workshop">확장 ${fmt(facilityCost('workshop'))}G</button></div><div class="economy-note"><b>골드 규칙</b> · 전투에서는 골드가 나오지 않습니다. 제작 시간과 상점 판매 시간은 모두 <b>판매가 × 3초</b>로 동일하게 계산됩니다.</div>${running.length?`<div class="job-list">${running.map(j=>`<div class="job-row"><span><b>${esc(j.output_item)} 제작 중</b><small>${esc((S.recipes||[]).find(r=>r.id===j.recipe_id)?.id||'제작')}</small></span><strong>${leftText(j.finish_at)}</strong></div>`).join('')}</div>`:''}<div class="recipe-list">${(S.recipes||[]).map(r=>{const locked=lv<Number(r.workshop_level||1),inputs=Object.entries(r.inputs||{}),short=inputs.some(([id,q])=>inventoryQty(id)<Number(q)),disabled=locked||short||queueFull;return `<div class="recipe-row ${locked?'locked':''}"><div class="recipe-icon">${itemSvg(itemAsset(r.output_item))}</div><div class="recipe-main"><b>${esc(r.output_item)}</b><div class="recipe-meta"><span>판매 <strong>${fmt(r.sale_gold)}G</strong></span><span>제작 ${secText(r.craft_seconds)}</span><span>판매 ${secText(r.sell_seconds)}</span></div><div class="recipe-inputs">${inputs.map(([id,q])=>`<span class="${inventoryQty(id)<Number(q)?'short':''}">${esc(id)} ${fmt(inventoryQty(id))}/${fmt(q)}</span>`).join('')}</div></div><button class="primary-btn" data-action="craft" data-id="${r.id}" ${disabled?'disabled':''}>${locked?`Lv.${r.workshop_level}`:queueFull?'대기열':'제작'}</button></div>`}).join('')}</div>`,'economy-sheet')}

function shopModal(){const running=(S.sellJobs||[]).find(x=>x.status==='running'),products=(S.recipes||[]).map(r=>({...r,qty:inventoryQty(r.output_item)})).filter(r=>r.qty>0);modal(`<div class="sheet-head"><div><div class="section-kicker">COMPANY SHOP</div><h2>상점</h2><p>제작이 끝난 제품만 골드로 바꿀 수 있습니다.</p></div><button class="close-btn" data-action="close">×</button></div><div class="economy-note">원재료는 직접 판매할 수 없습니다. <b>제작소에서 완제품으로 만든 뒤</b> 판매해야 합니다.</div>${running?`<div class="job-list"><div class="job-row"><span><b>${esc(running.item_id)} 판매 중</b><small>완료 시 ${fmt(running.sale_gold)}G 입금</small></span><strong>${leftText(running.finish_at)}</strong></div></div>`:''}<div class="shop-list">${products.length?products.map(r=>`<div class="shop-item"><div>${itemSvg(itemAsset(r.output_item))}</div><div><b>${esc(r.output_item)} × ${fmt(r.qty)}</b><small>판매가 <strong>${fmt(r.sale_gold)}G</strong> · ${secText(r.sell_seconds)}</small></div><button class="primary-btn" data-action="sell" data-id="${esc(r.output_item)}" ${running?'disabled':''}>판매</button></div>`).join(''):'<div class="shop-empty">판매 가능한 완제품이 없습니다.<br>제작소에서 먼저 제품을 생산하세요.</div>'}</div>`,'economy-sheet')}
"""
s=s.replace("\n\nfunction updateChrome",workshop_shop+"\nfunction updateChrome",1)

candidate="""function candidateModal(){const lv=Number(S.player.tavern_level||1);modal(`<div class="sheet-head"><div><div class="section-kicker">RECRUITING</div><h2>영입소</h2><p>4시간마다 영입소 Lv만큼 새 지원자가 교체되어 도착합니다.</p></div><button class="close-btn" data-action="close">×</button></div><div class="facility-upgrade"><span><small>영입소 Lv.${lv}</small><b>다음 배치 ${lv}명 · 높은 레벨일수록 A/S급 확률 상승</b></span><button class="soft-btn" data-action="upgrade" data-id="tavern">확장 ${fmt(nextTavernCost())}G</button></div><div class="candidate-list">${(S.candidates||[]).length?S.candidates.map(c=>`<div class="candidate-card"><div class="candidate-avatar">${charSvg(monsterAsset(c.family),'candidate-sprite')}</div><div><b><span class="candidate-grade ${esc(c.growth_grade||'C')}">${esc(c.growth_grade||'C')}</span>${esc(c.name)} · ${fam(c.family)}</b><small>재능 ${c.talent} · ${esc(c.personality||'침착')} · ${esc(c.trait||'무특성')}</small><span class="candidate-fit">HP ${fmt(c.hp_base)} · 공격 ${fmt(c.atk_base)} · 방어 ${fmt(c.def_base)}</span></div><div class="actions"><button class="primary-btn" data-action="hire" data-id="${c.id}">${fmt(c.hire_cost||0)}G 채용</button><button class="soft-btn" data-action="reject" data-id="${c.id}">거절</button></div></div>`).join(''):`<div class="empty-state">현재 대기 중인 지원자가 없습니다.<br>다음 배치까지 ${candidateText()}</div>`}</div>`,'recruit-sheet') }"""
s,n=re.subn(r"function candidateModal\(\).*?(?=\n\nfunction employeeModal)",candidate+"\n",s,count=1,flags=re.S)
if n!=1: raise SystemExit('candidate patch failed')

mission="""function missionModal(siteId,keep=false){const site=S.sites.find(x=>x.id===siteId);if(!site)return;if(!site.unlocked){toast('이전 지역 보스를 먼저 처치해야 합니다.');return}if(!keep||partySite!==siteId){partySite=siteId;partyPick=[]}const ex=activeAt(site.id),progress=site.progress||{},activeCount=(S.expeditions||[]).filter(e=>e.active).length,opsFull=activeCount>=Number(S.opsCapacity||1);partyPick=partyPick.filter(id=>!activeOf(id));const selected=S.monsters.filter(m=>partyPick.includes(m.id)),sumPower=selected.reduce((a,m)=>a+power(m),0);modal(`<div class="sheet-head"><div><div class="section-kicker">${siteCode(site.id)}</div><h2>${esc(site.name)}${progress.boss_ready?'<span class="boss-flag"> BOSS</span>':''}</h2><p>권장 전투력 ${fmt(site.recommended_power)} · 승리 ${fmt(Math.min(500,progress.normal_wins||0))}/500</p></div><button class="close-btn" data-action="close">×</button></div>${ex.length?`<div class="brief-list">${ex.map(e=>{const party=partyOf(e);return `<div class="brief-item mission-live-row"><span class="mini-avatar">${party[0]?charSvg(monsterAsset(party[0].family)):''}</span><div><b>${party.length}인 박멸조 · ${esc(partyLabel(e))}</b><small>${esc(e.phase||'탐색')} · 승리 ${fmt(e.kills)} · 화물 ${lootCount(e)}개</small><div class="party-avatars">${party.map(mm=>`<span class="party-avatar">${charSvg(monsterAsset(mm.family),'party-sprite')}</span>`).join('')}</div><div class="battle-actions"><button class="primary-btn" data-action="watch" data-id="${e.id}">관전</button><button class="danger-btn" data-action="recall" data-id="${e.id}">복귀</button></div></div></div>`}).join('')}</div>`:''}<div class="party-select-head"><b>파티 편성</b><small>최대 4마리 · 경험치 ${selected.length?`1/${selected.length}`:'-'}</small></div><div class="party-select-list">${S.monsters.map(m=>{const busy=!!activeOf(m.id),sel=partyPick.includes(m.id);return `<button class="party-select-row ${sel?'selected':''} ${busy?'busy':''}" data-action="toggle-party" data-id="${m.id}" data-site="${site.id}" ${busy?'disabled':''}><span>${charSvg(monsterAsset(m.family))}</span><span><b>${esc(m.name)} · Lv.${m.level} · ${esc(m.growth_grade||'C')}</b><small>${fam(m.family)} · 전투력 ${fmt(power(m))}${busy?' · 다른 작전 참가 중':''}</small></span><em>${sel?'선택':busy?'출동중':'+'}</em></button>`}).join('')}</div><div class="party-launch"><div class="party-summary"><span>${selected.length}/4 선택</span><span>합산 전투력 ${fmt(sumPower)}</span><span>${opsFull?'작전실 한도 초과':progress.boss_ready?'보스전 대기':'일반 탐사'}</span></div><button class="primary-btn" data-action="deploy-party" data-site="${site.id}" ${!selected.length||opsFull?'disabled':''}>${progress.boss_ready?'보스 박멸조 출정':'박멸조 출정'}</button></div>`,'mission-party-sheet') }"""
s,n=re.subn(r"function missionModal\(.*?(?=\nfunction battleUi)",mission+"\n",s,count=1,flags=re.S)
if n!=1: raise SystemExit('mission patch failed')

brief="""function briefModal(){const active=(S.expeditions||[]).filter(e=>e.active),craft=(S.craftJobs||[]).filter(x=>x.status==='running').length,sell=(S.sellJobs||[]).some(x=>x.status==='running');modal(`<div class="sheet-head"><div><div class="section-kicker">CONTROL ROOM BRIEF</div><h2>상황실 브리핑</h2><p>현재 회사 운영 핵심 흐름입니다.</p></div><button class="close-btn" data-action="close">×</button></div><div class="brief-list"><div class="brief-item"><i></i><div><b>전투 골드 0G</b><small>전리품을 제작소에서 가공하고 상점에서 판매해야 골드를 얻습니다.</small></div></div><div class="brief-item"><i></i><div><b>작전 ${active.length}/${S.opsCapacity||1} · 제작 ${craft}/${S.craftCapacity||1}</b><small>${sell?'상점 판매 진행 중':'상점은 현재 비어 있습니다.'}</small></div></div><div class="brief-item"><i></i><div><b>다음 지원자 ${candidateText()}</b><small>영입소 Lv.${S.player.tavern_level||1} 기준 한 번에 ${S.player.tavern_level||1}명이 도착합니다.</small></div></div><div class="brief-item"><i></i><div><b>회수 대기 화물 ${totalPending()}개</b><small>창고 ${inventoryUsed()}/${S.storageCapacity||40}</small></div></div></div>`)}"""
s,n=re.subn(r"function briefModal\(\).*?(?=\n\nfunction syncWatchPanel)",brief+"\n",s,count=1,flags=re.S)
if n!=1: raise SystemExit('brief patch failed')

handler="""document.addEventListener('click',async e=>{const nav=e.target.closest('[data-screen]');if(nav){screen=nav.dataset.screen;closeModal();render();return}const go=e.target.closest('[data-go]');if(go){screen=go.dataset.go;closeModal();render();return}const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='close'){closeModal();return}if(a==='menu'){menuModal();return}if(a==='brief'){briefModal();return}if(a==='candidates'){candidateModal();return}if(a==='dorm'){dormModal();return}if(a==='workshop'){workshopModal();return}if(a==='shop'){shopModal();return}if(a==='employee'){employeeModal(b.dataset.id);return}if(a==='personality'){personalityModal(b.dataset.id);return}if(a==='mission'){missionModal(b.dataset.id);return}if(a==='watch'){watchModal(b.dataset.id);return}if(a==='item'){itemModal(b.dataset.id);return}if(a==='toggle-party'){const id=b.dataset.id,site=b.dataset.site;if(activeOf(id)){toast('이미 다른 작전에 참가 중입니다.');return}if(partyPick.includes(id))partyPick=partyPick.filter(x=>x!==id);else{if(partyPick.length>=4){toast('파티는 최대 4마리입니다.');return}partyPick.push(id)}missionModal(site,true);return}if(a==='logout'){if(busy)return;busy=true;try{await sb.auth.signOut();showAuth()}finally{busy=false}return}try{busy=true;if(a==='deploy-party'){await api('deploy',{monsterIds:partyPick,siteId:b.dataset.site});closeModal();toast(`${partyPick.length||'파티'}마리 박멸조 출정`);render()}else if(a==='recall'){await api('recall',{expeditionId:b.dataset.id});closeModal();toast('박멸조가 본부로 복귀했습니다.');render()}else if(a==='collect-all'){await api('collect');toast('대기 화물을 모두 수령했습니다.');render()}else if(a==='collect-one'){await api('collect',{expeditionId:b.dataset.id});toast('화물을 창고로 옮겼습니다.');render()}else if(a==='craft'){await api('craft',{recipeId:b.dataset.id});workshopModal();toast('제작을 시작했습니다.')}else if(a==='sell'){await api('sell',{itemId:b.dataset.id});shopModal();toast('상점 판매를 시작했습니다.')}else if(a==='hire'){await api('hire',{candidateId:b.dataset.id});candidateModal();toast('신규 몬스터를 영입했습니다.')}else if(a==='reject'){await api('reject',{candidateId:b.dataset.id});candidateModal();toast('지원자를 돌려보냈습니다.')}else if(a==='equip'){await api('equip',{monsterId:b.dataset.id,itemId:b.dataset.item});closeModal();toast('장비를 장착했습니다.');render()}else if(a==='unequip'){await api('unequip',{monsterId:b.dataset.id,slot:b.dataset.slot});closeModal();toast('장비를 해제했습니다.');render()}else if(a==='upgrade'){await api('upgrade',{facility:b.dataset.id});closeModal();toast('시설 확장이 완료됐습니다.');render()}}catch(err){toast(errorKo(err.message))}finally{busy=false}});"""
s,n=re.subn(r"document\.addEventListener\('click'.*?(?=\n\nsb\.auth\.onAuthStateChange)",handler,s,count=1,flags=re.S)
if n!=1: raise SystemExit('handler patch failed')

p.write_text(s)

idx=Path('index.html')
h=idx.read_text().replace('v0.10.1','v0.11.0').replace('?v=0101','?v=0110')
needle='<link rel="stylesheet" href="detail-v0101.css?v=0110">'
if needle not in h: raise SystemExit('detail stylesheet anchor missing')
h=h.replace(needle,needle+'\n<link rel="stylesheet" href="economy-v011.css?v=0110">',1)
idx.write_text(h)
