from pathlib import Path


def block(src,start,end,new):
    i=src.index(start); j=src.index(end,i)
    return src[:i]+new+'\n\n'+src[j:]

p=Path('app.js')
s=p.read_text()

needle="const jobProgress=j=>{const a=new Date(j?.started_at||0).getTime(),b=new Date(j?.finish_at||0).getTime(),n=Date.now();if(!a||!b||b<=a)return 0;return Math.max(0,Math.min(100,(n-a)/(b-a)*100))};"
insert=needle+"\nconst activeCraftJobs=()=>[...(S?.craftJobs||[])].filter(x=>['running','queued'].includes(x.status)).sort((a,b)=>new Date(a.started_at)-new Date(b.started_at));\nconst activeSellJobs=()=>[...(S?.sellJobs||[])].filter(x=>['running','queued'].includes(x.status)).sort((a,b)=>new Date(a.started_at)-new Date(b.started_at));\nconst craftMaxQty=r=>{const a=Object.entries(r?.inputs||{}).map(([id,q])=>Math.floor(inventoryQty(id)/Math.max(1,Number(q||1))));return a.length?Math.max(0,Math.min(...a)):0};\nconst saleInfo=id=>{const r=recipeForOutput(id);if(r)return {item:id,unitGold:Number(r.sale_gold||0),unitSeconds:Math.max(1,Math.ceil(Number(r.craft_seconds||1)/1.2)),kind:'finished'};const d=rawSaleDef(id);return d?{item:id,unitGold:Number(d.sale_gold||0),unitSeconds:Number(d.sell_seconds||1),kind:'raw'}:null};"
if needle not in s: raise SystemExit('helper target missing')
s=s.replace(needle,insert,1)

s=block(s,'function hq(){','function dormModal(){',r'''function hq(){const active=(S.expeditions||[]).filter(e=>e.active),pending=totalPending(),cap=capacity(),used=inventoryUsed(),craftJobs=activeCraftJobs(),sellJobs=activeSellJobs();return `
<section class="facility-stack">
  <button class="facility-row dorm" data-action="dorm"><img src="assets/icon-dorm.svg" alt=""><span class="facility-copy"><b>숙소</b><small>${S.monsters.length}/${cap} 몬스터</small></span><span class="facility-side"><em>Lv.${S.player.quarters_level}</em><i>›</i></span></button>
  <button class="facility-row recruit" data-action="candidates"><img src="assets/icon-recruit.svg" alt=""><span class="facility-copy"><b>영입소</b><small>4시간마다 ${S.player.tavern_level}명 · 현재 ${(S.candidates||[]).length}명</small></span><span class="facility-side"><em>Lv.${S.player.tavern_level}</em><i>›</i></span></button>
  <button class="facility-row workshop" data-action="workshop"><img src="assets/icon-workshop.svg" alt=""><span class="facility-copy"><b>제작소</b><small>작업 ${craftJobs.length}/${S.craftCapacity||1} · 순차 생산</small></span><span class="facility-side"><em>Lv.${S.player.workshop_level||1}</em><i>›</i></span></button>
  <button class="facility-row shop" data-action="shop"><img src="assets/icon-shop.svg" alt=""><span class="facility-copy"><b>상점</b><small>판매 ${sellJobs.length}/${S.shopCapacity||1} · 순차 처리</small></span><span class="facility-side"><em>Lv.${S.player.shop_level||1}</em><i>›</i></span></button>
  <button class="facility-row storage" data-go="loot"><img src="assets/icon-storage.svg" alt=""><span class="facility-copy"><b>전리품 창고</b><small>${pending}개 회수 대기 · ${used}/${S.storageCapacity||40}</small></span><span class="facility-side"><em>Lv.${S.player.storage_level||1}</em><i>›</i></span></button>
  <button class="facility-row ops" data-go="hunt"><img src="assets/icon-ops.svg" alt=""><span class="facility-copy"><b>박멸 작전실</b><small>${active.length}/${S.opsCapacity||1}개 파티 출동</small></span><span class="facility-side"><em>Lv.${S.player.ops_level||1}</em><i>›</i></span></button>
</section>
${active.length?`<section class="home-live"><header><b>진행 중인 작전</b><small>${active.length}건</small></header>${active.slice(0,3).map(e=>{const site=S.sites.find(x=>x.id===e.site_id),p=partyOf(e);return `<button data-action="watch" data-id="${e.id}"><span class="live-pin"></span><span><b>${esc(site?.name||'작전')}</b><small>${esc(partyLabel(e))} · ${p.length}인 · 승리 ${fmt(e.kills)} · 화물 ${lootCount(e)}</small></span><i>관전</i></button>`}).join('')}</section>`:''}`}
''')

new_econ=r'''function economyJobRows(jobs,type){return jobs.length?`<div class="job-list">${jobs.map((j,i)=>{const waiting=new Date(j.started_at).getTime()>Date.now(),pct=jobProgress(j),qty=Number(type==='craft'?j.batch_qty:j.quantity||1);return `<div class="job-row craft-job ${waiting?'queued':''}" data-progress-start="${esc(j.started_at)}" data-progress-end="${esc(j.finish_at)}"><div class="job-copy"><b>${esc(type==='craft'?j.output_item:j.item_id)} × ${fmt(qty)} ${waiting?'대기':'진행 중'}</b><small>${waiting?`대기열 ${i}`:`<span class="job-percent">${Math.floor(pct)}%</span>`}</small><div class="craft-progress"><i class="craft-progress-fill" style="width:${waiting?0:pct}%"></i></div></div><strong class="job-left">${waiting?'대기 '+leftText(j.started_at):leftText(j.finish_at)}</strong></div>`}).join('')}</div>`:''}

function workshopModal(){const lv=Number(S.player.workshop_level||1),jobs=activeCraftJobs(),cap=Number(S.craftCapacity||lv),queueFull=jobs.length>=cap;modal(`<div class="sheet-head"><div><div class="section-kicker">WORKSHOP</div><h2>제작소</h2><p>한 품목을 원하는 수량만큼 묶어서 순차 생산합니다.</p></div><button class="close-btn" data-action="close">×</button></div><div class="facility-upgrade"><span><small>제작소 Lv.${lv}</small><b>현재 작업 1개 + 대기열 ${Math.max(0,cap-1)}개</b></span><button class="soft-btn" data-action="upgrade" data-id="workshop">확장 ${fmt(facilityCost('workshop'))}G</button></div><div class="economy-note">모든 제작법은 처음부터 사용 가능 · 제작시간은 <b>1개 기준 시간 × 수량</b> · 제작소 레벨은 제작법이 아니라 <b>대기열</b>을 늘립니다.</div>${economyJobRows(jobs,'craft')}<div class="recipe-list">${(S.recipes||[]).map(r=>{const inputs=Object.entries(r.inputs||{}),max=craftMaxQty(r),disabled=max<1||queueFull;return `<div class="recipe-row"><div class="recipe-icon">${itemSvg(itemAsset(r.output_item))}</div><div class="recipe-main"><b>${esc(r.output_item)}</b><div class="recipe-meta"><span>판매 <strong>${fmt(r.sale_gold)}G</strong></span><span>1개 제작 ${secText(r.craft_seconds)}</span><span>1개 판매 ${secText(Math.ceil(Number(r.craft_seconds||1)/1.2))}</span></div><div class="recipe-inputs">${inputs.map(([id,q])=>`<span class="${inventoryQty(id)<Number(q)?'short':''}">${esc(id)} ${fmt(inventoryQty(id))} / 개당 ${fmt(q)}</span>`).join('')}</div></div><button class="primary-btn" data-action="craft-setup" data-id="${r.id}" ${disabled?'disabled':''}>${queueFull?'대기열':'제작'}</button></div>`}).join('')}</div>`,'economy-sheet');updateEconomyProgress()}

function craftQuantityModal(recipeId){const r=(S.recipes||[]).find(x=>x.id===recipeId);if(!r)return;const max=craftMaxQty(r);if(max<1){toast('제작 재료가 부족합니다.');return}modal(`<div class="sheet-head"><div><div class="section-kicker">BATCH PRODUCTION</div><h2>${esc(r.output_item)} 제작</h2><p>1 ~ ${fmt(max)}개 중 생산 수량을 선택하세요.</p></div><button class="close-btn" data-action="close">×</button></div><div class="batch-picker"><div class="batch-hero">${itemSvg(itemAsset(r.output_item))}<span><small>선택 수량</small><b id="qtyValue">1개</b></span></div><input id="qtySlider" type="range" min="1" max="${max}" value="1" data-mode="craft" data-id="${r.id}"><div class="slider-scale"><span>1</span><span>최대 ${fmt(max)}</span></div><div id="qtySummary" class="batch-summary"></div><div class="qty-step"><button class="soft-btn" data-action="qty-dec">−</button><button class="soft-btn" data-action="qty-inc">＋</button></div><button class="primary-btn batch-confirm" data-action="craft-confirm" data-id="${r.id}">제작 대기열에 추가</button></div>`,'economy-sheet');updateQuantitySheet()}

function shopModal(){const lv=Number(S.player.shop_level||1),jobs=activeSellJobs(),cap=Number(S.shopCapacity||lv),queueFull=jobs.length>=cap,finished=(S.recipes||[]).map(r=>({...r,qty:inventoryQty(r.output_item),kind:'finished'})).filter(r=>r.qty>0),raw=(S.inventory||[]).map(x=>{const d=rawSaleDef(x.item_id);return d?{id:x.item_id,qty:Number(x.qty||0),sale_gold:Number(d.sale_gold||0),sell_seconds:Number(d.sell_seconds||0),kind:'raw'}:null}).filter(Boolean);const row=r=>{const id=r.output_item||r.id,si=saleInfo(id);return `<div class="shop-item ${r.kind==='raw'?'raw-sale':''}"><div>${itemSvg(itemAsset(id))}</div><div><b>${esc(id)} × ${fmt(r.qty)}</b><small>${r.kind==='raw'?'<em>원재료 직판</em> · ':''}개당 <strong>${fmt(si?.unitGold)}G</strong> · ${secText(si?.unitSeconds)}</small></div><button class="primary-btn" data-action="sell-setup" data-id="${esc(id)}" ${queueFull?'disabled':''}>${queueFull?'대기열':'판매'}</button></div>`};modal(`<div class="sheet-head"><div><div class="section-kicker">COMPANY SHOP</div><h2>상점</h2><p>판매 수량을 묶어서 지정하고 순차 판매합니다.</p></div><button class="close-btn" data-action="close">×</button></div><div class="facility-upgrade"><span><small>상점 Lv.${lv}</small><b>현재 판매 1개 + 대기열 ${Math.max(0,cap-1)}개</b></span><button class="soft-btn" data-action="upgrade" data-id="shop">확장 ${fmt(facilityCost('shop'))}G</button></div><div class="economy-note">완제품 판매 속도는 동일 품목 제작 속도의 <b>1.2배</b> · 판매시간은 대략 제작시간 ÷ 1.2입니다.</div>${economyJobRows(jobs,'sell')}<div class="shop-section-title"><b>완제품</b><small>가공 후 고수익 판매</small></div><div class="shop-list">${finished.length?finished.map(row).join(''):'<div class="shop-empty">판매 가능한 완제품이 없습니다.</div>'}</div><div class="shop-section-title raw"><b>원재료 직판</b><small>낮은 가격 · 긴급 현금화</small></div><div class="shop-list">${raw.length?raw.map(row).join(''):'<div class="shop-empty">직접 판매할 원재료가 없습니다.</div>'}</div>`,'economy-sheet');updateEconomyProgress()}

function sellQuantityModal(itemId){const si=saleInfo(itemId),max=inventoryQty(itemId);if(!si||max<1)return;modal(`<div class="sheet-head"><div><div class="section-kicker">BATCH SALE</div><h2>${esc(itemId)} 판매</h2><p>1 ~ ${fmt(max)}개 중 판매 수량을 선택하세요.</p></div><button class="close-btn" data-action="close">×</button></div><div class="batch-picker"><div class="batch-hero">${itemSvg(itemAsset(itemId))}<span><small>선택 수량</small><b id="qtyValue">1개</b></span></div><input id="qtySlider" type="range" min="1" max="${max}" value="1" data-mode="sell" data-id="${esc(itemId)}"><div class="slider-scale"><span>1</span><span>최대 ${fmt(max)}</span></div><div id="qtySummary" class="batch-summary"></div><div class="qty-step"><button class="soft-btn" data-action="qty-dec">−</button><button class="soft-btn" data-action="qty-inc">＋</button></div><button class="primary-btn batch-confirm" data-action="sell-confirm" data-id="${esc(itemId)}">판매 대기열에 추가</button></div>`,'economy-sheet');updateQuantitySheet()}

function updateQuantitySheet(){const r=$('#qtySlider'),sum=$('#qtySummary'),val=$('#qtyValue');if(!r||!sum||!val)return;const qty=Math.max(1,Math.min(Number(r.max||1),Number(r.value||1)));r.value=String(qty);val.textContent=`${fmt(qty)}개`;if(r.dataset.mode==='craft'){const x=(S.recipes||[]).find(v=>v.id===r.dataset.id);if(!x)return;sum.innerHTML=`<div><small>총 제작시간</small><b>${secText(Number(x.craft_seconds||0)*qty)}</b></div><div><small>완제품 가치</small><b>${fmt(Number(x.sale_gold||0)*qty)}G</b></div><div class="wide"><small>총 필요 재료</small><p>${Object.entries(x.inputs||{}).map(([id,n])=>`${esc(id)} <b>${fmt(Number(n)*qty)}</b> / 보유 ${fmt(inventoryQty(id))}`).join('<br>')}</p></div>`}else{const si=saleInfo(r.dataset.id);if(!si)return;sum.innerHTML=`<div><small>총 판매시간</small><b>${secText(si.unitSeconds*qty)}</b></div><div><small>총 입금액</small><b>${fmt(si.unitGold*qty)}G</b></div><div class="wide"><small>판매 수량</small><p>${fmt(qty)}개 / 보유 ${fmt(inventoryQty(r.dataset.id))}개</p></div>`}}
'''
s=block(s,'function workshopModal(){','function updateChrome(){',new_econ)

old="function updateEconomyProgress(){document.querySelectorAll('[data-progress-start][data-progress-end]').forEach(el=>{const a=new Date(el.dataset.progressStart).getTime(),b=new Date(el.dataset.progressEnd).getTime(),n=Date.now(),pct=!a||!b||b<=a?0:Math.max(0,Math.min(100,(n-a)/(b-a)*100)),fill=el.querySelector('.craft-progress-fill'),pc=el.querySelector('.job-percent'),left=el.querySelector('.job-left');if(fill)fill.style.width=pct+'%';if(pc)pc.textContent=Math.floor(pct)+'%';if(left)left.textContent=secText(Math.max(0,(b-n)/1000))})}"
new="function updateEconomyProgress(){document.querySelectorAll('[data-progress-start][data-progress-end]').forEach(el=>{const a=new Date(el.dataset.progressStart).getTime(),b=new Date(el.dataset.progressEnd).getTime(),n=Date.now(),waiting=n<a,pct=waiting?0:(!a||!b||b<=a?0:Math.max(0,Math.min(100,(n-a)/(b-a)*100))),fill=el.querySelector('.craft-progress-fill'),pc=el.querySelector('.job-percent'),left=el.querySelector('.job-left');if(fill)fill.style.width=pct+'%';if(pc)pc.textContent=waiting?'대기':Math.floor(pct)+'%';if(left)left.textContent=waiting?'대기 '+secText((a-n)/1000):secText(Math.max(0,(b-n)/1000))})}"
if old not in s: raise SystemExit('progress target missing')
s=s.replace(old,new,1)

s=s.replace("if(a==='item'){itemModal(b.dataset.id);return}","if(a==='item'){itemModal(b.dataset.id);return}if(a==='craft-setup'){craftQuantityModal(b.dataset.id);return}if(a==='sell-setup'){sellQuantityModal(b.dataset.id);return}if(a==='qty-dec'||a==='qty-inc'){const q=$('#qtySlider');if(q){q.value=String(Math.max(Number(q.min||1),Math.min(Number(q.max||1),Number(q.value||1)+(a==='qty-inc'?1:-1))));updateQuantitySheet()}return}",1)
s=s.replace("else if(a==='craft'){await api('craft',{recipeId:b.dataset.id});workshopModal();toast('제작을 시작했습니다.')}else if(a==='sell'){await api('sell',{itemId:b.dataset.id});shopModal();toast('상점 판매를 시작했습니다.')}","else if(a==='craft-confirm'){const qty=Number($('#qtySlider')?.value||1);await api('craft',{recipeId:b.dataset.id,quantity:qty});workshopModal();toast(`${fmt(qty)}개 제작 예약`)}else if(a==='sell-confirm'){const qty=Number($('#qtySlider')?.value||1);await api('sell',{itemId:b.dataset.id,quantity:qty});shopModal();toast(`${fmt(qty)}개 판매 예약`)}",1)

marker="sb.auth.onAuthStateChange((_event,newSession)=>{session=newSession});"
if marker not in s: raise SystemExit('input marker missing')
s=s.replace(marker,"document.addEventListener('input',e=>{if(e.target?.id==='qtySlider')updateQuantitySheet()});\n"+marker,1)
s=s.replace("workshop_level:'제작소 레벨이 부족합니다.',","")
s=s.replace("not_sellable:'제작품만 상점에 판매할 수 있습니다.'","not_sellable:'판매할 수 없는 품목입니다.'")
p.write_text(s)

css=Path('economy-v011.css')
c=css.read_text()
add=r'''

/* v0.11.4 — batch crafting/selling and sequential queues */
.job-row.queued{opacity:.78;border-style:dashed}.job-row.queued .craft-progress-fill{background:#666f67}.batch-picker{display:grid;gap:10px}.batch-hero{height:58px;display:flex;align-items:center;gap:10px;border:1px solid #3d473f;background:#151a16;padding:7px}.batch-hero>.pixel-item{width:42px;height:42px}.batch-hero small{display:block;font-size:8px;color:#87928a}.batch-hero b{display:block;margin-top:2px;font-size:18px;color:#efbc74}.batch-picker input[type=range]{width:100%;accent-color:#c58b47}.slider-scale{display:flex;justify-content:space-between;margin-top:-6px;font-size:8px;color:#7f8a82}.batch-summary{display:grid;grid-template-columns:1fr 1fr;gap:5px}.batch-summary>div{border:1px solid #354038;background:#111612;padding:8px}.batch-summary>div.wide{grid-column:1/-1}.batch-summary small{display:block;font-size:7px;color:#7d8980}.batch-summary b{display:block;margin-top:2px;font-size:12px;color:#e8b56e}.batch-summary p{margin:4px 0 0;font-size:9px;line-height:1.65;color:#aeb7b0}.batch-summary p b{display:inline;font-size:9px}.qty-step{display:grid;grid-template-columns:1fr 1fr;gap:6px}.qty-step button{height:36px;font-size:18px}.batch-confirm{width:100%;min-height:42px}.shop-item button,.recipe-row button{white-space:nowrap}.facility-row.shop .facility-side em{color:#e4b465}
'''
if 'v0.11.4 — batch crafting' not in c: c+=add
css.write_text(c)

idx=Path('index.html')
h=idx.read_text().replace('v0.11.3','v0.11.4').replace('?v=0113','?v=0114')
idx.write_text(h)
