from pathlib import Path
import re

p=Path('app.js')
s=p.read_text()

s=s.replace("const power=m=>Math.floor(Number(m.power_base||0)+(Number(m.level||1)-1)*12+Math.max(0,Number(m.talent||80)-80)*1.2);",'''const itemDef=id=>(S?.itemDefs||[]).find(x=>x.id===id)||null;
const equippedFor=mid=>(S?.equipment||[]).filter(x=>x.monster_id===mid);
const monsterStats=m=>{const eq=equippedFor(m.id).map(x=>itemDef(x.item_id)).filter(Boolean),sum=k=>eq.reduce((a,x)=>a+Number(x[k]||0),0);return {hp:Math.round(Number(m.hp_base||120)+(Number(m.level||1)-1)*9+Math.max(0,Number(m.talent||80)-80)*2+sum('hp')),atk:Math.round(Number(m.atk_base||18)+(Number(m.level||1)-1)*2+Math.max(0,Number(m.talent||80)-80)*.22+sum('atk')),def:Math.round(Number(m.def_base||8)+(Number(m.level||1)-1)*.8+sum('def')),spd:Math.round(Number(m.spd_base||10)+(Number(m.level||1)-1)*.18+sum('spd')),crit:Number(m.crit_base||.05)+sum('crit'),evade:Number(m.evade_base||.03)+sum('evade'),human:sum('human_damage')}};
const power=m=>{const st=monsterStats(m);return Math.floor(Number(m.power_base||0)+(Number(m.level||1)-1)*12+Math.max(0,Number(m.talent||80)-80)*1.2+(st.atk-Number(m.atk_base||18))*.8+(st.def-Number(m.def_base||8))*.55+(st.hp-Number(m.hp_base||120))*.03)};
const slotName=s=>({weapon:'무기',armor:'방어구',accessory:'장신구'}[s]||s);
const rarityClass=r=>({'일반':'normal','고급':'uncommon','희귀':'rare','영웅':'epic'}[r]||'normal');''')

s=s.replace("const itemAsset=n=>{const x=String(n||'');if(/동전/.test(x))return 'coin';if(/천/.test(x))return 'cloth';if(/몽둥이/.test(x))return 'club';if(/주머니/.test(x))return 'pouch';if(/가죽/.test(x))return 'leather';if(/낫/.test(x))return 'sickle';if(/철/.test(x))return 'iron';if(/검/.test(x))return 'sword';return 'crate'};", "const itemAsset=n=>{const x=String(n||'');if(/동전/.test(x))return 'coin';if(/천/.test(x))return 'cloth';if(/몽둥이/.test(x))return 'club';if(/주머니|부적|훈장/.test(x))return 'pouch';if(/가죽|조끼/.test(x))return 'leather';if(/낫/.test(x))return 'sickle';if(/철|철갑/.test(x))return 'iron';if(/검/.test(x))return 'sword';return 'crate'};")

s=s.replace("server_error:'서버 처리 중 오류가 발생했습니다.'", "not_equipment:'장착할 수 없는 물품입니다.',item_missing:'창고에 해당 장비가 없습니다.',server_error:'서버 처리 중 오류가 발생했습니다.'")

employee='''function employeeModal(id){const m=S.monsters.find(x=>x.id===id);if(!m)return;const e=activeOf(m.id),site=e&&S.sites.find(x=>x.id===e.site_id),st=monsterStats(m),eq=equippedFor(m.id);const gear=['weapon','armor','accessory'].map(slot=>{const row=eq.find(x=>x.slot===slot),d=row&&itemDef(row.item_id);return `<div class="gear-slot ${d?rarityClass(d.rarity):'empty'}"><small>${slotName(slot)}</small>${d?`<b>${itemSvg(itemAsset(d.id))}${esc(d.id)}</b><button data-action="unequip" data-id="${m.id}" data-slot="${slot}">해제</button>`:`<b>비어 있음</b><span>창고 장비를 선택해 장착</span>`}</div>`}).join('');modal(`<div class="sheet-head"><div><div class="section-kicker">MONSTER FILE</div><h2>${esc(m.name)}</h2><p>${fam(m.family)} · ${roleOf(m)} · 성장 ${esc(m.growth_grade||'C')}</p></div><button class="close-btn" data-action="close">×</button></div><div class="monster-profile-v10"><div class="monster-identity"><div class="detail-portrait">${charSvg(monsterAsset(m.family),'detail-sprite')}</div><div><span class="personality-tag">${esc(m.personality||'침착')}</span><b>${esc(m.trait||'무특성')}</b><small>재능 ${fmt(m.talent)} · 누적 박멸 ${fmt(m.kills)}</small></div></div><div class="combat-stat-grid"><div><small>HP</small><b>${fmt(st.hp)}</b></div><div><small>공격</small><b>${fmt(st.atk)}</b></div><div><small>방어</small><b>${fmt(st.def)}</b></div><div><small>속도</small><b>${fmt(st.spd)}</b></div><div><small>치명</small><b>${Math.round(st.crit*100)}%</b></div><div><small>회피</small><b>${Math.round(st.evade*100)}%</b></div></div><div class="gear-grid">${gear}</div><div class="detail-note compact"><b>${e?'현장 근무 중':'본부 대기'}</b><br>${e?`${esc(site?.name||'현장')} · 현재 ${esc(e.phase||'탐색')} 단계`:'박멸 작전실에서 현장에 배치할 수 있습니다.'}</div></div>${e?`<div class="battle-actions"><button class="primary-btn" data-action="watch" data-id="${e.id}">현장 보기</button></div>`:''}`,'monster-detail-sheet-v10')}'''
s=re.sub(r"function employeeModal\(id\)\{.*?\n\nfunction missionModal",employee+"\n\nfunction missionModal",s,flags=re.S)

loot='''function loot(){const groups=(S.expeditions||[]).filter(e=>lootCount(e)>0),total=totalPending();return `
<div class="compact-head"><div><b>전리품 창고</b><small>${total}개 수령 대기</small></div><button class="primary-btn" data-action="collect-all" ${total?'':'disabled'}>전체 수령</button></div>
${groups.length?groups.map(e=>{const m=S.monsters.find(x=>x.id===e.monster_id),site=S.sites.find(x=>x.id===e.site_id);return `<section class="warehouse-group compact-warehouse"><header><span><b>${esc(site?.name||'현장')}</b><small>${esc(m?.name||'몬스터')} · ${lootCount(e)}개 · ${esc(e.phase||'탐색')}</small></span><button class="soft-btn" data-action="collect-one" data-id="${e.id}">수령</button></header><div class="shelf">${Object.entries(e.pending_loot||{}).map(([name,qty])=>`<div class="item-bin compact-item"><div class="item-art">${itemSvg(itemAsset(name))}</div><b>${esc(name)}</b><strong>${fmt(qty)}</strong></div>`).join('')}</div></section>`}).join(''):`<div class="empty-state warehouse-empty"><div>${itemSvg('crate')}</div><b>대기 화물 없음</b></div>`}
<section class="inventory-card"><div class="compact-head inner"><b>보관 재고</b><small>장비는 눌러서 장착</small></div><div class="inventory-grid">${(S.inventory||[]).length?S.inventory.map(x=>{const d=itemDef(x.item_id);return `<button class="inventory-slot ${d?.slot?'equippable '+rarityClass(d.rarity):''}" data-action="item" data-id="${esc(x.item_id)}"><div class="item-art small">${itemSvg(itemAsset(x.item_id))}</div><b>${esc(x.item_id)}</b><small>${fmt(x.qty)}${d?.slot?' · '+slotName(d.slot):''}</small></button>`}).join(''):'<div class="empty-state" style="grid-column:1/-1">비어 있음</div>'}</div></section>`}'''
s=re.sub(r"function loot\(\)\{.*?\n\n\nfunction updateChrome",loot+"\n\n\nfunction updateChrome",s,flags=re.S)

item_modal='''function itemModal(itemId){const inv=(S.inventory||[]).find(x=>x.item_id===itemId),d=itemDef(itemId);if(!inv)return;if(!d?.slot){modal(`<div class="sheet-head"><div><div class="section-kicker">WAREHOUSE ITEM</div><h2>${esc(itemId)}</h2><p>보유 ${fmt(inv.qty)}개</p></div><button class="close-btn" data-action="close">×</button></div><div class="material-detail">${itemSvg(itemAsset(itemId))}<b>재료/전리품</b><p>현재는 장착할 수 없습니다. 향후 제작·판매 시스템에서 사용됩니다.</p></div>`);return}const bonus=[d.atk&&`공격 +${d.atk}`,d.def&&`방어 +${d.def}`,d.hp&&`HP +${d.hp}`,d.spd&&`속도 ${d.spd>0?'+':''}${d.spd}`,Number(d.crit)&&`치명 +${Math.round(Number(d.crit)*100)}%`,Number(d.evade)&&`회피 +${Math.round(Number(d.evade)*100)}%`,Number(d.human_damage)&&`인간 피해 +${Math.round(Number(d.human_damage)*100)}%`].filter(Boolean).join(' · ');modal(`<div class="sheet-head"><div><div class="section-kicker">EQUIPMENT</div><h2>${esc(itemId)}</h2><p>${esc(d.rarity)} · ${slotName(d.slot)} · 보유 ${fmt(inv.qty)}</p></div><button class="close-btn" data-action="close">×</button></div><div class="equipment-detail ${rarityClass(d.rarity)}"><div class="equipment-icon">${itemSvg(itemAsset(itemId))}</div><div><b>${esc(bonus||'특수 능력 없음')}</b><p>${esc(d.description||'')}</p></div></div><div class="equip-target-list">${S.monsters.map(m=>{const current=equippedFor(m.id).find(x=>x.slot===d.slot);return `<button data-action="equip" data-id="${m.id}" data-item="${esc(itemId)}"><span>${charSvg(monsterAsset(m.family),'mini-equip-char')}</span><span><b>${esc(m.name)}</b><small>${current?'현재 '+esc(current.item_id):slotName(d.slot)+' 비어 있음'}</small></span><em>장착</em></button>`}).join('')}</div>`,'item-detail-sheet-v10')}'''
s=s.replace("function menuModal(){",item_modal+"\n\nfunction menuModal(){")

battle_log='''function battleLogHtml(e,m,site){const rows=(e.battle_log||[]).slice(0,12);if(!rows.length)return '<div class="combat-log-empty">첫 현장 기록을 기다리는 중...</div>';return rows.map(x=>{if(x.type==='explore')return `<div class="combat-log-row explore"><b>${esc(x.phase||'탐색')}</b> · ${esc(x.event||'현장을 살피는 중')}${Number(x.loot)>0?` <em>전리품 +${fmt(x.loot)}</em>`:''}</div>`;const enemy=esc(x.enemy||'용사'),role=esc(x.enemyRole||'인간');if(x.result==='win')return `<div class="combat-log-row"><b class="ally">${esc(m.name)}</b> vs <b class="enemy">${enemy}</b> <small>${role}</small><br><strong>${fmt(x.damageDealt||0)}</strong> 피해 · 받은 피해 ${fmt(x.damageTaken||0)}${Number(x.crits)>0?` <em>치명 ${fmt(x.crits)}회</em>`:''}${Number(x.dodges)>0?` <em>회피 ${fmt(x.dodges)}회</em>`:''}</div><div class="combat-log-row system">박멸 성공${Number(x.loot)>0?` · 화물 ${fmt(x.loot)}개 확보`:''}</div>`;return `<div class="combat-log-row fail"><b class="enemy">${enemy}</b>에게 밀려남 · <b class="ally">${esc(m.name)}</b> 피해 ${fmt(x.damageTaken||0)}</div>`}).join('')}'''
s=re.sub(r"function battleLogHtml\(e,m,site\)\{.*?\nfunction watchModal",battle_log+"\nfunction watchModal",s,flags=re.S)

watch='''function watchModal(expId){const e=S.expeditions.find(x=>x.id===expId);if(!e)return;const m=S.monsters.find(x=>x.id===e.monster_id),site=S.sites.find(x=>x.id===e.site_id),bs=e.battle_state||{},enemy=bs.enemy||site?.enemy_names?.[0]||'용사',ui=battleUi(e.site_id),mhp=Number(bs.monsterHp||0),mmax=Number(bs.monsterMaxHp||monsterStats(m).hp),ehp=Number(bs.enemyHp||0),emax=Number(bs.enemyMaxHp||1),mpct=Math.max(0,Math.min(100,mmax?mhp/mmax*100:100)),epct=Math.max(0,Math.min(100,emax?ehp/emax*100:100));watchingExpeditionId=expId;modal(`<div class="battle-report-head"><div><h2>${esc(site?.name||'현장')}</h2><small>${siteCode(e.site_id)} · ${esc(e.phase||'탐색')} · 탐사 ${fmt(e.exploration_count||0)}</small></div><button class="battle-report-close" data-action="close">×</button></div><div class="battle-report-scene ${e.site_id}"><div class="battle-scene-top"><span class="battle-opcode">${siteCode(e.site_id)}</span><span class="battle-server-badge">SERVER LIVE</span></div><div class="battle-party"><div class="battle-actor monster-actor"><div class="actor-frame">${m?charSvg(monsterAsset(m.family),'battle-sprite'):''}</div><span class="battle-name">${esc(m?.name||'몬스터')}</span><span class="battle-hp"><i id="liveMonsterHp" style="width:${mpct}%"></i></span><small id="liveMonsterHpText" class="hp-text">${fmt(mhp||mmax)}/${fmt(mmax)}</small></div><div class="battle-impact"></div><div id="liveDamageFloat" class="battle-dmg-float">-${fmt(bs.damageDealt||0)}</div><div class="battle-actor enemy-actor"><div id="liveEnemySprite" class="actor-frame">${charSvg(enemyAsset(enemy),'battle-sprite')}</div><span id="liveEnemyName" class="battle-name">${esc(enemy)} · ${esc(bs.enemyRole||'인간')}</span><span class="battle-hp"><i id="liveEnemyHp" style="width:${epct}%"></i></span><small id="liveEnemyHpText" class="hp-text">${fmt(ehp)}/${fmt(emax)}</small></div></div></div><div class="battle-report-body"><div id="liveAlert" class="battle-alert">${esc(e.event_state?.text||ui.alert)}</div><div class="battle-zone-copy"><span>${esc(ui.copy)}</span></div><div class="battle-summary"><div><small>현재 단계</small><b id="livePhase">${esc(e.phase||'탐색')}</b></div><div><small>박멸</small><b><span id="liveKills">${fmt(e.kills)}</span>명</b></div><div><small>회수 화물</small><b><span id="liveLoot">${lootCount(e)}</span>개</b></div></div><div id="liveLog" class="combat-log">${battleLogHtml(e,m,site)}</div></div><div class="battle-report-actions"><button class="retreat" data-action="recall" data-id="${e.id}">현장 철수</button><button class="close" data-action="close">닫기</button></div>`,'battle-report-sheet');syncWatchPanel()}'''
s=re.sub(r"function watchModal\(expId\)\{.*?\n\nfunction itemModal",watch+"\n\nfunction itemModal",s,flags=re.S)

sync='''function syncWatchPanel(){if(!watchingExpeditionId||!S)return;const e=S.expeditions.find(x=>x.id===watchingExpeditionId);if(!e)return;const m=S.monsters.find(x=>x.id===e.monster_id),site=S.sites.find(x=>x.id===e.site_id),bs=e.battle_state||{},enemy=bs.enemy||site?.enemy_names?.[0]||'용사',ui=battleUi(e.site_id),mhp=Number(bs.monsterHp||0),mmax=Number(bs.monsterMaxHp||monsterStats(m).hp),ehp=Number(bs.enemyHp||0),emax=Number(bs.enemyMaxHp||1);const k=$('#liveKills'),l=$('#liveLoot'),n=$('#liveEnemyName'),log=$('#liveLog'),holder=$('#liveEnemySprite'),alert=$('#liveAlert'),dmg=$('#liveDamageFloat'),phase=$('#livePhase'),mh=$('#liveMonsterHp'),eh=$('#liveEnemyHp'),mht=$('#liveMonsterHpText'),eht=$('#liveEnemyHpText');if(k)k.textContent=fmt(e.kills);if(l)l.textContent=lootCount(e);if(n)n.textContent=enemy+' · '+(bs.enemyRole||'인간');if(alert)alert.textContent=e.event_state?.text||ui.alert;if(dmg)dmg.textContent='-'+fmt(bs.damageDealt||0);if(phase)phase.textContent=e.phase||'탐색';if(mh)mh.style.width=`${Math.max(0,Math.min(100,mmax?mhp/mmax*100:100))}%`;if(eh)eh.style.width=`${Math.max(0,Math.min(100,emax?ehp/emax*100:100))}%`;if(mht)mht.textContent=`${fmt(mhp||mmax)}/${fmt(mmax)}`;if(eht)eht.textContent=`${fmt(ehp)}/${fmt(emax)}`;if(holder){const u=holder.querySelector('use');if(u)u.setAttribute('href',`assets/characters.svg#${enemyAsset(enemy)}`)}if(log&&m)log.innerHTML=battleLogHtml(e,m,site)}'''
s=re.sub(r"function syncWatchPanel\(\)\{.*?\n\nasync function refresh",sync+"\n\nasync function refresh",s,flags=re.S)

s=s.replace("if(a==='watch'){watchModal(b.dataset.id);return}","if(a==='watch'){watchModal(b.dataset.id);return}if(a==='item'){itemModal(b.dataset.id);return}")
s=s.replace("else if(a==='upgrade'){await api('upgrade',{facility:b.dataset.id});toast('시설 확장이 완료됐습니다.');render()}","else if(a==='equip'){await api('equip',{monsterId:b.dataset.id,itemId:b.dataset.item});closeModal();toast('장비를 장착했습니다.');render()}else if(a==='unequip'){await api('unequip',{monsterId:b.dataset.id,slot:b.dataset.slot});closeModal();toast('장비를 해제했습니다.');render()}else if(a==='upgrade'){await api('upgrade',{facility:b.dataset.id});toast('시설 확장이 완료됐습니다.');render()}")

# Operation card shows current exploration phase.
s=s.replace("${ex.length?`교전 ${battle} · 화물 ${pending}`:(unlocked?'배치 가능':'잠김')}","${ex.length?`${esc(ex[0]?.phase||'탐색')} · 교전 ${battle} · 화물 ${pending}`:(unlocked?'배치 가능':'잠김')}")

p.write_text(s)

idx=Path('index.html')
t=idx.read_text().replace('v0.9.4','v0.10.0').replace('v0940','v0100').replace('</head>','<link rel="stylesheet" href="detail-v010.css?v=0100">\n</head>')
idx.write_text(t)
