-- Generated by node tools/build-campaign-runtime.mjs
create or replace function public.game_species_template(p_family text) returns jsonb language sql immutable set search_path=public as $$select '{"slime":{"family":"slime","name":"슬라임","role":"균형","hp":145,"atk":15,"def":11,"spd":9,"crit":0.04,"evade":0.03,"power":45,"skill":null,"description":"질긴 체력으로 첫 영업을 책임지는 만능 신입."},"goblin":{"family":"goblin","name":"고블린","role":"공격","hp":100,"atk":21,"def":7,"spd":14,"crit":0.08,"evade":0.06,"power":52,"skill":null,"description":"빠른 선공과 치명타에 강한 현장 영업사원."},"troll":{"family":"troll","name":"트롤","role":"공격","hp":175,"atk":24,"def":13,"spd":7,"crit":0.05,"evade":0.02,"power":68,"skill":null,"description":"느리지만 튼튼한 근접 공격 담당."},"mandrake":{"family":"mandrake","name":"만드라고라","role":"회복","hp":125,"atk":12,"def":9,"spd":10,"crit":0.03,"evade":0.04,"power":50,"skill":"healing_spore","description":"주기적인 포자 회복으로 장기 근무를 돕는 복지 담당."},"pixie":{"family":"pixie","name":"픽시","role":"회복","hp":78,"atk":10,"def":4,"spd":17,"crit":0.03,"evade":0.12,"power":48,"skill":"emergency_glimmer","description":"빠르고 회피가 높지만 체력이 낮은 응급 지원 담당."},"imp":{"family":"imp","name":"임프","role":"마법","hp":86,"atk":22,"def":5,"spd":11,"crit":0.06,"evade":0.04,"power":54,"skill":"arcane_bolt","description":"두꺼운 인간 갑옷을 관통하는 마법 공격 담당."},"wisp":{"family":"wisp","name":"위습","role":"마법","hp":76,"atk":21,"def":4,"spd":16,"crit":0.06,"evade":0.1,"power":53,"skill":"mana_spark","description":"속도와 회피를 활용하는 기동 마법 담당."},"golem":{"family":"golem","name":"골렘","role":"방어","hp":240,"atk":13,"def":21,"spd":5,"crit":0.02,"evade":0.01,"power":63,"skill":"guardian_slam","description":"도발과 피해 감소로 동료를 지키는 보안 담당."},"mimic":{"family":"mimic","name":"미믹","role":"방어","hp":185,"atk":20,"def":17,"spd":6,"crit":0.04,"evade":0.01,"power":62,"skill":"bait_counter","description":"도발과 반격을 겸하는 이동식 회사 금고."}}'::jsonb->p_family$$;
revoke all on function public.game_species_template(text) from public,anon,authenticated;
grant execute on function public.game_species_template(text) to service_role;

-- campaign-support.sql
-- Campaign progression extends existing records; never reset a player's clears.
-- v0.15 writes contextual text including actual recovery and loot. The old
-- presentation trigger overwrote it with generic strings and removed those facts.
drop trigger if exists trg_game_chapter_event_text on public.game_expeditions;
alter table public.game_stage_progress add column if not exists normal_battles bigint not null default 0;
alter table public.game_stage_progress add column if not exists boss_victories bigint not null default 0;
alter table public.game_stage_progress add column if not exists first_boss_cleared_at timestamptz;
alter table public.game_stage_progress add column if not exists last_boss_attempt_at timestamptz;
alter table public.game_stage_progress add column if not exists boss_last_result text;
alter table public.game_stage_progress add column if not exists boss_history jsonb not null default '[]'::jsonb;
update public.game_stage_progress set boss_victories=greatest(1,boss_victories),
  first_boss_cleared_at=coalesce(first_boss_cleared_at,boss_cleared_at)
where boss_cleared;
-- Old wins are confirmed completed battles. Historical losses were not counted
-- separately, so do not invent them. Previously unlocked/cleared bosses stay open.
update public.game_stage_progress set normal_battles=greatest(normal_battles,normal_wins),
  boss_ready=boss_ready or boss_cleared or normal_wins>=500;

create or replace function public.game_boss_encounter_roll(p_unlocked boolean,p_chance numeric default 0.015)
returns boolean language sql volatile set search_path=public as $$
  select coalesce(p_unlocked,false) and random()<greatest(0,least(0.02,coalesce(p_chance,0.015)))
$$;

create or replace function public.game_roll_ground_item(p_loot jsonb)
returns jsonb language plpgsql volatile set search_path=public as $$
declare row jsonb; total numeric; cursor numeric:=0; roll numeric;
begin
  select coalesce(sum((value->>'chance')::numeric),0) into total
  from jsonb_array_elements(p_loot) where value->>'source'='scavenge';
  if total<=0 then return null; end if;
  roll:=random()*total;
  for row in select value from jsonb_array_elements(p_loot) where value->>'source'='scavenge' loop
    cursor:=cursor+coalesce((row->>'chance')::numeric,0);
    if roll<cursor then return row; end if;
  end loop;
  return null;
end $$;

-- Pure loot roll used by combat and probability tests. Legendary rows share one
-- weighted roll, so their displayed marginal probabilities are exact and at most
-- one legendary can drop per kill. Ordinary foes have no legendary rows.
create or replace function public.game_roll_campaign_drops(p_loot jsonb,p_enemy text,p_bonus numeric default 0)
returns jsonb language plpgsql volatile set search_path=public as $$
declare row jsonb; result jsonb:='{}'; quantity int; probability numeric;
  bonus numeric:=1+greatest(0,least(0.20,coalesce(p_bonus,0)));
  legend_roll numeric:=random(); legend_cumulative numeric:=0;
begin
  for row in select value from jsonb_array_elements(p_loot)
    where value->>'source'='kill' and value->>'enemy' in ('*',p_enemy)
  loop
    probability:=least(0.95,greatest(0,(row->>'chance')::numeric)*bonus);
    if row->>'pool'='legendary' then
      legend_cumulative:=legend_cumulative+probability;
      if legend_roll>=legend_cumulative or legend_roll<legend_cumulative-probability then continue; end if;
    elsif random()>=probability then continue;
    end if;
    quantity:=coalesce((row->>'min')::int,1)+floor(random()*(coalesce((row->>'max')::int,1)-coalesce((row->>'min')::int,1)+1))::int;
    result:=jsonb_set(result,array[row->>'id'],to_jsonb(coalesce((result->>(row->>'id'))::int,0)+quantity));
  end loop;
  return result;
end $$;

-- Rare finds use the equipment case, separate from bulk material cargo. They
-- remain pending until collection; a full warehouse never deletes them.
create or replace function public.game_add_pending_loot(p_expedition uuid,p_item text,p_qty integer)
returns void language plpgsql set search_path=public as $$
declare owner_id uuid; site text; kind text; site_total bigint; add_qty bigint; cur bigint;
begin
  select player_id,site_id into owner_id,site from public.game_expeditions where id=p_expedition;
  if owner_id is null then return; end if;
  select d.kind into kind from public.game_item_defs d where d.id=p_item;
  if kind is null then return; end if;
  perform pg_advisory_xact_lock(hashtextextended(owner_id::text||':'||site,0));
  add_qty:=greatest(0,coalesce(p_qty,0));
  if kind<>'equipment' then
    select coalesce(sum(j.value::bigint),0) into site_total
    from public.game_expeditions ge
    cross join lateral jsonb_each_text(coalesce(ge.pending_loot,'{}'::jsonb)) j(key,value)
    left join public.game_item_defs d on d.id=j.key
    where ge.player_id=owner_id and ge.site_id=site and coalesce(d.kind,'material')<>'equipment';
    add_qty:=least(add_qty,greatest(0,public.game_site_loot_capacity(owner_id,site)-site_total));
  end if;
  if add_qty<=0 then return; end if;
  select coalesce((pending_loot->>p_item)::bigint,0) into cur from public.game_expeditions where id=p_expedition for update;
  update public.game_expeditions set pending_loot=jsonb_set(coalesce(pending_loot,'{}'::jsonb),array[p_item],to_jsonb(cur+add_qty),true),updated_at=now() where id=p_expedition;
end $$;

create or replace function public.game_award_campaign_drops(p_expedition uuid,p_drops jsonb)
returns jsonb language plpgsql set search_path=public as $$
declare row record; before_loot jsonb; after_loot jsonb; result jsonb:='{}'; actual int;
begin
  select pending_loot into before_loot from public.game_expeditions where id=p_expedition for update;
  for row in select key,value from jsonb_each_text(p_drops) loop
    perform public.game_add_pending_loot(p_expedition,row.key,row.value::int);
  end loop;
  select pending_loot into after_loot from public.game_expeditions where id=p_expedition;
  for row in select key,value from jsonb_each_text(p_drops) loop
    actual:=coalesce((after_loot->>row.key)::int,0)-coalesce((before_loot->>row.key)::int,0);
    if actual>0 then result:=jsonb_set(result,array[row.key],to_jsonb(actual)); end if;
  end loop;
  return result;
end $$;

revoke all on function public.game_roll_ground_item(jsonb) from public,anon,authenticated;
revoke all on function public.game_add_pending_loot(uuid,text,integer) from public,anon,authenticated;
grant execute on function public.game_add_pending_loot(uuid,text,integer) to service_role;
revoke all on function public.game_roll_campaign_drops(jsonb,text,numeric) from public,anon,authenticated;
revoke all on function public.game_award_campaign_drops(uuid,jsonb) from public,anon,authenticated;
revoke all on function public.game_boss_encounter_roll(boolean,numeric) from public,anon,authenticated;
grant execute on function public.game_roll_ground_item(jsonb),public.game_roll_campaign_drops(jsonb,text,numeric),public.game_award_campaign_drops(uuid,jsonb) to service_role;
grant execute on function public.game_boss_encounter_roll(boolean,numeric) to service_role;


-- roster-support.sql
-- Candidate stats must survive hiring exactly as previewed. The legacy BEFORE
-- INSERT trigger overwrote three families' stats, grades and personalities.
drop trigger if exists trg_game_monster_detail_defaults on public.game_monsters;
alter table public.game_players add column if not exists starter_support_offered boolean not null default false;

create or replace function public.game_spawn_candidates()
returns integer language plpgsql set search_path=public as $$
declare p record; i int; r numeric; grade text; family text; template jsonb;
  personality text; trait text; talent int; multiplier numeric;
  made int:=0; locked_count int; new_count int;
begin
  for p in select * from public.game_players where next_candidate_at<=now() for update skip locked loop
    delete from public.game_candidates where player_id=p.device_id and not coalesce(is_locked,false);
    select count(*) into locked_count from public.game_candidates where player_id=p.device_id and coalesce(is_locked,false);
    new_count:=greatest(0,greatest(4,p.tavern_level+3)-locked_count);
    for i in 1..new_count loop
      r:=random();
      grade:=case when p.tavern_level<=1 then case when r<0.65 then 'C' when r<0.95 then 'B' else 'A' end
        when p.tavern_level=2 then case when r<0.45 then 'C' when r<0.85 then 'B' when r<0.99 then 'A' else 'S' end
        when p.tavern_level=3 then case when r<0.25 then 'C' when r<0.70 then 'B' when r<0.97 then 'A' else 'S' end
        when p.tavern_level=4 then case when r<0.10 then 'C' when r<0.50 then 'B' when r<0.93 then 'A' else 'S' end
        else case when r<0.35 then 'B' when r<0.85 then 'A' else 'S' end end;
      -- An unlocked batch always includes recovery, defense and damage choices.
      -- Player-locked candidates keep their original slots and data.
      family:=case i when 1 then (array['mandrake','pixie'])[1+floor(random()*2)::int]
        when 2 then (array['golem','mimic'])[1+floor(random()*2)::int]
        when 3 then (array['goblin','troll','imp','wisp'])[1+floor(random()*4)::int]
        else (array['slime','goblin','troll','mandrake','pixie','imp','wisp','golem','mimic'])[1+floor(random()*9)::int] end;
      template:=public.game_species_template(family);
      personality:=(array['침착','약탈광','광전사','겁쟁이','인간혐오','야행성'])[1+floor(random()*6)::int];
      trait:=(array['질긴 가죽','야성','재빠름','수집광','학습 본능'])[1+floor(random()*5)::int];
      talent:=least(100,greatest(0,p.tavern_level-1)+case grade when 'S' then 94+floor(random()*7)::int when 'A' then 88+floor(random()*10)::int when 'B' then 82+floor(random()*11)::int else 76+floor(random()*12)::int end);
      multiplier:=case grade when 'S' then 1.16 when 'A' then 1.10 when 'B' then 1.05 else 1 end;
      insert into public.game_candidates(player_id,name,family,talent,trait,power_base,personality,growth_grade,hp_base,atk_base,def_base,spd_base,crit_base,evade_base,is_locked)
      values(p.device_id,template->>'name',family,talent,trait,(template->>'power')::int,personality,grade,
        round((template->>'hp')::numeric*multiplier),round((template->>'atk')::numeric*multiplier),round((template->>'def')::numeric*multiplier),round((template->>'spd')::numeric*multiplier),(template->>'crit')::numeric,(template->>'evade')::numeric,false);
      made:=made+1;
    end loop;
    update public.game_players set next_candidate_at=now()+interval '4 hours',updated_at=now() where device_id=p.device_id;
  end loop;
  return made;
end $$;

-- Service-role-only bootstrap: one transaction prevents half-created companies.
-- Repeated login cannot farm starter employees or candidate refreshes.
create or replace function public.game_initialize_company(p_player uuid)
returns void language plpgsql set search_path=public as $$
declare created boolean:=false; offered boolean; template jsonb; family text;
begin
  insert into public.game_players(device_id,device_secret_hash) values(p_player,null) on conflict do nothing;
  created:=found;
  select starter_support_offered into offered from public.game_players where device_id=p_player for update;
  if created then
    insert into public.game_monsters(player_id,name,family,form_id,evolution_tier,level,xp,talent,trait,power_base,hp_base,atk_base,def_base,spd_base,crit_base,evade_base,personality,growth_grade)
    values(p_player,'슬라임','slime','slime',0,1,0,88,'질긴 가죽',48,145,15,11,9,0.04,0.03,'침착','B');
  end if;
  if not offered then
    -- Existing developed companies need no starter offer. A new or stalled
    -- company with no candidates can choose support immediately on login.
    if not exists(select 1 from public.game_candidates where player_id=p_player)
      and (select count(*) from public.game_monsters where player_id=p_player and released_at is null)<3 then
      foreach family in array array['mandrake','imp','golem'] loop
        template:=public.game_species_template(family);
        insert into public.game_candidates(player_id,name,family,talent,trait,power_base,personality,growth_grade,hp_base,atk_base,def_base,spd_base,crit_base,evade_base,is_locked)
        values(p_player,template->>'name',family,86,'학습 본능',(template->>'power')::int,'침착','B',
          (template->>'hp')::int,(template->>'atk')::int,(template->>'def')::int,(template->>'spd')::int,(template->>'crit')::numeric,(template->>'evade')::numeric,false);
      end loop;
      update public.game_players set next_candidate_at=now()+interval '4 hours' where device_id=p_player;
    end if;
    update public.game_players set starter_support_offered=true where device_id=p_player;
  end if;
end $$;
revoke all on function public.game_initialize_company(uuid) from public,anon,authenticated;
grant execute on function public.game_initialize_company(uuid) to service_role;


-- economy-support.sql
-- Consistent warehouse, workshop and facility economy. Internal functions are
-- called through the authenticated Edge API; manual claim RPCs retain auth.uid.
-- Use the existing global tick lock so manual claims and automatic completion
-- cannot spend or award the same inventory/currency concurrently.
create or replace function public.game_upgrade_facility(p_player uuid,p_facility text,p_expected_level integer default null)
returns jsonb language plpgsql set search_path=public as $$
declare p public.game_players%rowtype; field_name text; current_level integer; price bigint; maximum integer;
begin
  perform pg_advisory_xact_lock(hashtextextended('game_tick_all',0));
  field_name:=case p_facility when 'quarters' then 'quarters_level' when 'tavern' then 'tavern_level' when 'storage' then 'storage_level' when 'workshop' then 'workshop_level' when 'shop' then 'shop_level' end;
  if field_name is null then raise exception 'facility'; end if;
  select * into p from public.game_players where device_id=p_player for update;
  if not found then raise exception 'player_missing'; end if;
  current_level:=(to_jsonb(p)->>field_name)::integer;
  if p_expected_level is not null and p_expected_level<>current_level then raise exception 'facility_changed'; end if;
  maximum:=case when p_facility='quarters' then 8 else 5 end;
  if current_level>=maximum then raise exception 'max_level'; end if;
  price:=(case p_facility when 'quarters' then 900 when 'tavern' then 1800 when 'storage' then 1200 when 'workshop' then 1600 when 'shop' then 1500 end)*power(3::numeric,greatest(0,current_level-1));
  if p.gold<price then raise exception 'gold_short'; end if;
  execute format('update public.game_players set gold=gold-$1,%I=$2,updated_at=now() where device_id=$3',field_name) using price,current_level+1,p_player;
  return jsonb_build_object('facility',p_facility,'level',current_level+1,'cost',price);
end $$;
revoke all on function public.game_upgrade_facility(uuid,text,integer) from public,anon,authenticated;
grant execute on function public.game_upgrade_facility(uuid,text,integer) to service_role;
create or replace function public.game_storage_capacity(p_player uuid)
returns integer language sql stable set search_path=public as $$
  select case when storage_level<=1 then 40 when storage_level=2 then 80 when storage_level=3 then 140 when storage_level=4 then 220 else 350+greatest(0,storage_level-5)*150 end from game_players where device_id=p_player
$$;
create or replace function public.game_inventory_accepts(p_player uuid,p_item text)
returns boolean language sql stable set search_path=public as $$
  select exists(select 1 from game_inventory where player_id=p_player and item_id=p_item and qty>0)
    or (select count(*) from game_inventory where player_id=p_player and qty>0)<game_storage_capacity(p_player)
$$;
revoke all on function public.game_storage_capacity(uuid),public.game_inventory_accepts(uuid,text) from public,anon,authenticated;
grant execute on function public.game_storage_capacity(uuid),public.game_inventory_accepts(uuid,text) to service_role;
CREATE OR REPLACE FUNCTION public.game_start_craft(p_player uuid, p_recipe text, p_qty integer)
 RETURNS uuid
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  r record;
  kv record;
  have bigint;
  queued_count int;
  queue_cap int;
  job_id uuid;
  scheduled_start timestamptz;
  scheduled_finish timestamptz;
  total_need bigint;
  spend jsonb:='{}'::jsonb;
begin
  perform pg_advisory_xact_lock(hashtextextended('game_tick_all',0));
  perform public.game_process_economy();
  if coalesce(p_qty,0)<1 then raise exception 'quantity_invalid'; end if;
  select * into r from public.game_recipes where id=p_recipe;
  if r.id is null then raise exception 'recipe_missing'; end if;
  if not exists(select 1 from public.game_players where device_id=p_player and workshop_level>=r.workshop_level) then raise exception 'workshop_level'; end if;

  select greatest(5,coalesce(workshop_level,1)+4) into queue_cap
  from public.game_players where device_id=p_player;
  select count(*) into queued_count
  from public.game_craft_jobs where player_id=p_player and status in ('running','queued');
  if queued_count>=queue_cap then raise exception 'craft_queue_full'; end if;

  select coalesce(jsonb_object_agg(k.key,to_jsonb((k.value::bigint*p_qty::bigint)::bigint)),'{}'::jsonb)
  into spend from jsonb_each_text(r.inputs) k;

  for kv in select key,value from jsonb_each_text(spend) loop
    select coalesce(qty,0) into have from public.game_inventory where player_id=p_player and item_id=kv.key;
    if coalesce(have,0)<kv.value::bigint then raise exception 'material_short'; end if;
  end loop;

  for kv in select key,value from jsonb_each_text(spend) loop
    update public.game_inventory set qty=qty-kv.value::bigint where player_id=p_player and item_id=kv.key;
    delete from public.game_inventory where player_id=p_player and item_id=kv.key and qty<=0;
  end loop;

  select greatest(now(),coalesce(max(finish_at),now())) into scheduled_start
  from public.game_craft_jobs where player_id=p_player and status in ('running','queued');
  scheduled_finish:=scheduled_start+make_interval(secs=>r.craft_seconds*p_qty);

  insert into public.game_craft_jobs(player_id,recipe_id,output_item,output_qty,batch_qty,started_at,finish_at,status,materials_spent)
  values(p_player,r.id,r.output_item,r.output_qty*p_qty,p_qty,scheduled_start,scheduled_finish,
         case when scheduled_start<=now() then 'running' else 'queued' end,spend)
  returning id into job_id;
  return job_id;
end
$function$
;

CREATE OR REPLACE FUNCTION public.game_start_sell(p_player uuid, p_item text, p_qty integer)
 RETURNS uuid
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare r record; d record; have bigint; queued_count int; queue_cap int; job_id uuid; unit_price int; unit_seconds int; scheduled_start timestamptz; scheduled_finish timestamptz;
begin
  perform pg_advisory_xact_lock(hashtextextended('game_tick_all',0));
 perform public.game_process_economy(); if coalesce(p_qty,0)<1 then raise exception 'quantity_invalid'; end if;
 select * into r from public.game_recipes where output_item=p_item order by sort_order limit 1; if r.id is not null then unit_price:=r.sale_gold;unit_seconds:=greatest(1,ceil(r.craft_seconds/1.2)::integer); else select * into d from public.game_item_defs where id=p_item and kind='material' and sale_gold>0 limit 1; if d.id is null then raise exception 'not_sellable';end if;unit_price:=d.sale_gold;unit_seconds:=greatest(1,d.sell_seconds);end if;
 select greatest(5,coalesce(shop_level,1)+4) into queue_cap from public.game_players where device_id=p_player; select count(*) into queued_count from public.game_sell_jobs where player_id=p_player and status in ('running','queued'); if queued_count>=queue_cap then raise exception 'sell_queue_full'; end if;
 select coalesce(qty,0) into have from public.game_inventory where player_id=p_player and item_id=p_item; if coalesce(have,0)<p_qty then raise exception 'item_missing'; end if; update public.game_inventory set qty=qty-p_qty where player_id=p_player and item_id=p_item; delete from public.game_inventory where player_id=p_player and item_id=p_item and qty<=0;
 select greatest(now(),coalesce(max(finish_at),now())) into scheduled_start from public.game_sell_jobs where player_id=p_player and status in ('running','queued'); scheduled_finish:=scheduled_start+make_interval(secs=>unit_seconds*p_qty);
 insert into public.game_sell_jobs(player_id,item_id,sale_gold,quantity,started_at,finish_at,status) values(p_player,p_item,unit_price*p_qty,p_qty,scheduled_start,scheduled_finish,case when scheduled_start<=now() then 'running' else 'queued' end) returning id into job_id; return job_id;
end $function$
;

CREATE OR REPLACE FUNCTION public.game_claim_craft(p_job uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare j record; v_player uuid; manual_mode boolean;
begin
  perform pg_advisory_xact_lock(hashtextextended('game_tick_all',0));
  v_player:=auth.uid();
  if v_player is null then raise exception 'unauthorized'; end if;
  select manual_economy_claim into manual_mode from public.game_players where device_id=v_player;
  if coalesce(manual_mode,false)=false then raise exception 'manual_mode_disabled'; end if;
  perform public.game_process_economy();
  select * into j from public.game_craft_jobs where id=p_job and player_id=v_player for update;
  if j.id is null then raise exception 'job_missing'; end if;
  if j.status='done' then raise exception 'job_already_claimed'; end if;
  if j.status<>'ready' then raise exception 'job_not_ready'; end if;
  if not public.game_inventory_accepts(v_player,j.output_item) then raise exception 'storage_full'; end if;
  insert into public.game_inventory(player_id,item_id,qty)
  values(j.player_id,j.output_item,j.output_qty)
  on conflict(player_id,item_id) do update set qty=public.game_inventory.qty+excluded.qty;
  update public.game_craft_jobs set status='done' where id=j.id;
  return jsonb_build_object('jobId',j.id,'itemId',j.output_item,'quantity',j.output_qty);
end
$function$
;

CREATE OR REPLACE FUNCTION public.game_claim_sell(p_job uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare j record; v_player uuid; manual_mode boolean;
begin
  perform pg_advisory_xact_lock(hashtextextended('game_tick_all',0));
  v_player:=auth.uid();
  if v_player is null then raise exception 'unauthorized'; end if;
  select manual_economy_claim into manual_mode from public.game_players where device_id=v_player;
  if coalesce(manual_mode,false)=false then raise exception 'manual_mode_disabled'; end if;
  perform public.game_process_economy();
  select * into j from public.game_sell_jobs where id=p_job and player_id=v_player for update;
  if j.id is null then raise exception 'job_missing'; end if;
  if j.status='done' then raise exception 'job_already_claimed'; end if;
  if j.status<>'ready' then raise exception 'job_not_ready'; end if;
  update public.game_players set gold=gold+j.sale_gold,updated_at=now() where device_id=j.player_id;
  update public.game_sell_jobs set status='done' where id=j.id;
  return jsonb_build_object('jobId',j.id,'itemId',j.item_id,'quantity',j.quantity,'gold',j.sale_gold);
end
$function$
;

CREATE OR REPLACE FUNCTION public.game_process_economy()
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare j record; n integer:=0; manual_mode boolean;
begin
  perform pg_advisory_xact_lock(hashtextextended('game_tick_all',0));
  for j in
    select * from public.game_craft_jobs
    where status in ('running','queued','ready') and finish_at<=now()
    order by finish_at
    for update skip locked
  loop
    select coalesce(manual_economy_claim,false) into manual_mode from public.game_players where device_id=j.player_id;
    if manual_mode or not public.game_inventory_accepts(j.player_id,j.output_item) then
      if j.status<>'ready' then
        update public.game_craft_jobs set status='ready',completed_at=coalesce(completed_at,finish_at) where id=j.id;
        n:=n+1;
      end if;
    else
      insert into public.game_inventory(player_id,item_id,qty)
      values(j.player_id,j.output_item,j.output_qty)
      on conflict(player_id,item_id) do update set qty=public.game_inventory.qty+excluded.qty;
      update public.game_craft_jobs set status='done',completed_at=coalesce(completed_at,now()) where id=j.id;
      n:=n+1;
    end if;
  end loop;

  update public.game_craft_jobs set status='running'
  where status='queued' and started_at<=now() and finish_at>now();

  for j in
    select * from public.game_sell_jobs
    where status in ('running','queued','ready') and finish_at<=now()
    order by finish_at
    for update skip locked
  loop
    select coalesce(manual_economy_claim,false) into manual_mode from public.game_players where device_id=j.player_id;
    if manual_mode then
      if j.status<>'ready' then
        update public.game_sell_jobs set status='ready',completed_at=coalesce(completed_at,finish_at) where id=j.id;
        n:=n+1;
      end if;
    else
      update public.game_players set gold=gold+j.sale_gold,updated_at=now() where device_id=j.player_id;
      update public.game_sell_jobs set status='done',completed_at=coalesce(completed_at,now()) where id=j.id;
      n:=n+1;
    end if;
  end loop;

  update public.game_sell_jobs set status='running'
  where status='queued' and started_at<=now() and finish_at>now();
  return n;
end
$function$
;

CREATE OR REPLACE FUNCTION public.game_collect_loot(p_player uuid, p_expedition uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  e record;
  kv record;
  total jsonb := '{}'::jsonb;
  cur bigint;
  q bigint;
begin
  perform pg_advisory_xact_lock(hashtextextended('game_tick_all',0));
  if exists(select 1 from public.game_expeditions where id=p_expedition and player_id<>p_player) then raise exception 'invalid_target'; end if;
  if (select count(*) from public.game_inventory where player_id=p_player and qty>0)+(select count(distinct l.key) from public.game_expeditions ge cross join lateral jsonb_each_text(ge.pending_loot) l where ge.player_id=p_player and (p_expedition is null or ge.id=p_expedition) and l.value::bigint>0 and not exists(select 1 from public.game_inventory i where i.player_id=p_player and i.item_id=l.key and i.qty>0))>public.game_storage_capacity(p_player) then raise exception 'storage_full'; end if;
  for e in
    select * from public.game_expeditions
    where player_id=p_player and (p_expedition is null or id=p_expedition)
    for update
  loop
    for kv in select key,value from jsonb_each_text(coalesce(e.pending_loot,'{}'::jsonb)) loop
      q:=kv.value::bigint;
      if q>0 then
        insert into public.game_inventory(player_id,item_id,qty)
        values(p_player,kv.key,q)
        on conflict(player_id,item_id) do update
          set qty=public.game_inventory.qty+excluded.qty;
        cur:=coalesce((total->>kv.key)::bigint,0);
        total:=jsonb_set(total,array[kv.key],to_jsonb(cur+q),true);
      end if;
    end loop;

    update public.game_expeditions
    set pending_loot='{}'::jsonb,
        pending_xp='{}'::jsonb,
        last_loot_collected_at=now(),
        updated_at=now()
    where id=e.id;
  end loop;
  return total;
end
$function$
;


-- game_process_expedition_action.sql
CREATE OR REPLACE FUNCTION public.game_process_expedition_action(p_expedition uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  e record;
  mem record;
  party_n int:=0;
  living_n int:=0;
  event_roll numeric;
  phase_now text;
  event_text text;
  enemy text;
  enemy_role text;
  is_boss boolean:=false;
  boss_ready_v boolean:=false;
  boss_cleared_v boolean:=false;
  enemy_profile jsonb:='{}'::jsonb;
  enemy_skill jsonb:='{}'::jsonb;
  enemy_skill_active boolean:=false;
  enemy_skill_damage numeric:=1;
  enemy_skill_ignore numeric:=0;
  enemy_healed int:=0;
  drops_json jsonb:='{}'::jsonb;
  progress_wins bigint:=0;
  enemy_power numeric;
  group_hp_scale numeric;
  group_atk_scale numeric;
  party_spd numeric:=0;
  initiative_chance numeric:=0.5;
  turn_side text;
  round_i int:=1;
  party_hp_json jsonb:='{}'::jsonb;
  party_max_json jsonb:='{}'::jsonb;
  attack_counts jsonb:='{}'::jsonb;
  bs jsonb:='{}'::jsonb;
  newstate jsonb:='{}'::jsonb;
  newlog jsonb:='[]'::jsonb;
  log_entry jsonb:='{}'::jsonb;
  last_action jsonb:='{}'::jsonb;
  skill_events jsonb:='[]'::jsonb;
  death_events jsonb:='[]'::jsonb;
  loot_row jsonb;
  recovery jsonb;
  recovery_text text;
  exp_hp_ratio numeric:=1;
  loot_gained int:=0;
  qty int;
  chance numeric;
  search_bonus numeric:=0;
  party_loot numeric:=0;
  growth numeric;
  lvl int;
  mhp numeric;
  matk numeric;
  mdef numeric;
  mspd numeric;
  mcrit numeric;
  mevade numeric;
  mhuman numeric;
  current_hp int;
  max_hp int;
  attack_no int;
  enemy_hp int;
  enemy_hp_max int;
  enemy_atk numeric;
  enemy_def numeric;
  enemy_spd numeric;
  enemy_crit numeric;
  enemy_evade numeric;
  dmg int:=0;
  total_dmg int:=0;
  crits int:=0;
  dodges int:=0;
  enemy_crits int:=0;
  dealt_total int:=0;
  taken_total int:=0;
  skill_fx jsonb;
  skill_mult numeric:=1;
  skill_ignore numeric:=0;
  skill_name text;
  skill_owner text;
  skill_effect text:='damage';
  heal_ratio numeric:=0;
  heal_target_id uuid;
  heal_target_name text;
  heal_target_max int:=0;
  heal_before int:=0;
  heal_after int:=0;
  heal_amount int:=0;
  heal_total int:=0;
  turn_heal int:=0;
  armor_coeff numeric:=0.55;
  target_id uuid;
  target_name text;
  hp_before int;
  hp_after int;
  xp_lost int:=0;
  won boolean:=false;
  lost boolean:=false;
  xp_each int;
  xp_amt int;
begin
  select x.*,s.recommended_power,s.xp_per_kill,s.enemy_names,s.loot,s.boss_name,s.boss_power,s.chapter
  into e
  from public.game_expeditions x
  join public.game_hunt_sites s on s.id=x.site_id
  where x.id=p_expedition and x.active=true
  for update of x;
  if not found then return jsonb_build_object('type','inactive'); end if;

  select count(*) into party_n from public.game_expedition_members where expedition_id=e.id;
  if party_n<=0 then
    insert into public.game_expedition_members(expedition_id,player_id,monster_id,position)
    values(e.id,e.player_id,e.monster_id,1) on conflict do nothing;
    party_n:=1;
  end if;
  insert into public.game_stage_progress(player_id,site_id) values(e.player_id,e.site_id) on conflict do nothing;

  bs:=coalesce(e.battle_state,'{}'::jsonb);
  if not coalesce((bs->>'active')::boolean,false) then
    exp_hp_ratio:=public.game_expedition_hp_ratio(bs);
    event_roll:=random();
    /* Wounded parties become cautious instead of chain-pulling enemies forever. */
    if event_roll>=0.72 then
      if exp_hp_ratio<0.35 and random()<0.82 then event_roll:=0.60;
      elsif exp_hp_ratio<0.60 and random()<0.57 then event_roll:=0.60;
      end if;
    end if;
    loot_gained:=0;
    if event_roll<0.28 then
      phase_now:='수색';
      event_text:=coalesce(e.chapter->>'search','주변을 수색한다');
      select greatest(coalesce(max(case when m.personality='약탈광' then 0.15 else 0 end),0),coalesce(max(case when m.trait='수집광' then 0.10 else 0 end),0))
      into search_bonus from public.game_expedition_members em join public.game_monsters m on m.id=em.monster_id where em.expedition_id=e.id;
      if random()<least(0.35,0.10+coalesce(search_bonus,0)*0.50) then
        loot_row:=public.game_roll_ground_item(e.loot);
        if loot_row is not null then
          drops_json:=public.game_award_campaign_drops(e.id,jsonb_build_object(loot_row->>'id',1));
          loot_gained:=coalesce((drops_json->>(loot_row->>'id'))::int,0);
          event_text:=event_text||case when loot_gained>0 then ' · '||(loot_row->>'id')||' 발견' else ' · 재료 적재 한도 도달' end;
        end if;
      end if;
      recovery:=public.game_roll_exploration_recovery(e.id,bs);bs:=coalesce(recovery->'state',bs);recovery_text:=coalesce(recovery->>'text','');if recovery_text<>'' then event_text:=event_text||' · '||recovery_text;end if;
      log_entry:=jsonb_build_object('t',now(),'type','explore','phase',phase_now,'event',event_text,'loot',loot_gained,'drops',drops_json,'recovery',coalesce(recovery,'{}'::jsonb)-'state','partyCount',party_n);
      update public.game_expeditions set phase=phase_now,exploration_count=exploration_count+1,event_state=jsonb_build_object('type','search','text',event_text,'loot',loot_gained,'t',now()),battle_state=bs,updated_at=now() where id=e.id;
    elsif event_roll<0.48 then
      phase_now:='전리품 수거';
      loot_row:=public.game_roll_ground_item(e.loot);
      if loot_row is not null and random()<0.18 then
        qty:=1;
        drops_json:=public.game_award_campaign_drops(e.id,jsonb_build_object(loot_row->>'id',qty));
        loot_gained:=coalesce((drops_json->>(loot_row->>'id'))::int,0);
        event_text:=case when loot_gained>0 then '주변에 남겨진 '||(loot_row->>'id')||' '||loot_gained||'개를 회수했다' else '재료 적재 한도 도달 · 전리품을 먼저 수거하세요' end;
      else
        event_text:='회수할 만한 전리품을 찾지 못했다';
      end if;
      recovery:=public.game_roll_exploration_recovery(e.id,bs);bs:=coalesce(recovery->'state',bs);recovery_text:=coalesce(recovery->>'text','');if recovery_text<>'' then event_text:=event_text||' · '||recovery_text;end if;
      log_entry:=jsonb_build_object('t',now(),'type','explore','phase',phase_now,'event',event_text,'loot',loot_gained,'drops',drops_json,'recovery',coalesce(recovery,'{}'::jsonb)-'state','partyCount',party_n);
      update public.game_expeditions set phase=phase_now,exploration_count=exploration_count+1,event_state=jsonb_build_object('type','loot','text',event_text,'loot',loot_gained,'t',now()),battle_state=bs,updated_at=now() where id=e.id;
    elsif event_roll<0.72 then
      phase_now:='이동';
      event_text:=coalesce(e.chapter->>'move','다음 구역으로 이동한다');
      recovery:=public.game_roll_exploration_recovery(e.id,bs);bs:=coalesce(recovery->'state',bs);recovery_text:=coalesce(recovery->>'text','');if recovery_text<>'' then event_text:=event_text||' · '||recovery_text;end if;
      log_entry:=jsonb_build_object('t',now(),'type','explore','phase',phase_now,'event',event_text,'recovery',coalesce(recovery,'{}'::jsonb)-'state','partyCount',party_n);
      update public.game_expeditions set phase=phase_now,exploration_count=exploration_count+1,event_state=jsonb_build_object('type','move','text',event_text,'t',now()),battle_state=bs,updated_at=now() where id=e.id;
    else
      select boss_ready,boss_cleared,normal_battles into boss_ready_v,boss_cleared_v,progress_wins from public.game_stage_progress where player_id=e.player_id and site_id=e.site_id for update;
      is_boss:=public.game_boss_encounter_roll(coalesce(boss_ready_v,false) or coalesce(boss_cleared_v,false) or progress_wins>=500,coalesce((e.chapter->>'bossChance')::numeric,0.015));
      enemy:=case when is_boss then e.boss_name else e.enemy_names[1+floor(random()*array_length(e.enemy_names,1))::int] end;
      enemy_profile:=coalesce(e.chapter->'profiles'->enemy,'{}'::jsonb);
      enemy_role:=coalesce(enemy_profile->>'role',case when is_boss then '보스' else '민병' end);
      if is_boss then
        update public.game_stage_progress set boss_ready=true,boss_attempts=boss_attempts+1,last_boss_attempt_at=now(),boss_last_result='encounter',updated_at=now() where player_id=e.player_id and site_id=e.site_id;
      end if;
      enemy_power:=case when is_boss then e.boss_power else e.recommended_power end;
      party_spd:=0;living_n:=0;party_hp_json:=coalesce(bs->'partyHp','{}'::jsonb);party_max_json:='{}'::jsonb;attack_counts:='{}'::jsonb;
      for mem in
        select m.*,coalesce(eq.eq_hp,0) eq_hp,coalesce(eq.eq_spd,0) eq_spd,coalesce(eq.eq_evade,0) eq_evade
        from public.game_expedition_members em join public.game_monsters m on m.id=em.monster_id
        left join lateral (select sum(d.hp*(1+coalesce(q.enhance_level,0)*0.08)) eq_hp,sum(d.spd*(1+coalesce(q.enhance_level,0)*0.08)) eq_spd,sum(d.evade*(1+coalesce(q.enhance_level,0)*0.08)) eq_evade from public.game_monster_equipment q join public.game_item_defs d on d.id=q.item_id where q.monster_id=m.id) eq on true
        where em.expedition_id=e.id order by em.position
      loop
        growth:=case mem.growth_grade when 'S' then 1.21 when 'A' then 1.13 when 'B' then 1.06 else 1 end;lvl:=greatest(1,mem.level);
        mhp:=mem.hp_base+(lvl-1)*9*growth+greatest(0,mem.talent-80)*2+mem.eq_hp;
        mspd:=mem.spd_base+(lvl-1)*0.18*growth+mem.eq_spd;
        if mem.trait='재빠름' then mspd:=mspd*1.08;end if;
        if mem.personality='겁쟁이' then mspd:=mspd*1.05;elsif mem.personality='야행성' and (extract(hour from now() at time zone 'Asia/Seoul')>=18 or extract(hour from now() at time zone 'Asia/Seoul')<6) then mspd:=mspd*1.12;end if;
        max_hp:=greatest(1,round(mhp)::int);current_hp:=coalesce((party_hp_json->>mem.id::text)::int,max_hp);current_hp:=least(max_hp,greatest(0,current_hp));party_hp_json:=jsonb_set(party_hp_json,array[mem.id::text],to_jsonb(current_hp),true);party_max_json:=jsonb_set(party_max_json,array[mem.id::text],to_jsonb(max_hp),true);attack_counts:=jsonb_set(attack_counts,array[mem.id::text],'0'::jsonb,true);if current_hp>0 then party_spd:=party_spd+mspd;living_n:=living_n+1;end if;
      end loop;
      party_spd:=party_spd/greatest(1,living_n);
      group_hp_scale:=0.8+0.35*(greatest(1,living_n)-1);group_atk_scale:=0.9+0.20*(greatest(1,living_n)-1);
      enemy_hp_max:=greatest(25,round(coalesce((enemy_profile->>'hp')::numeric,enemy_power*1.4)*group_hp_scale)::int);
      enemy_atk:=greatest(5,coalesce((enemy_profile->>'atk')::numeric,enemy_power*0.44)*group_atk_scale);
      enemy_def:=coalesce((enemy_profile->>'def')::numeric,enemy_power*0.17);
      enemy_spd:=coalesce((enemy_profile->>'spd')::numeric,9);enemy_crit:=coalesce((enemy_profile->>'crit')::numeric,0.05);enemy_evade:=coalesce((enemy_profile->>'evade')::numeric,0.03);
      initiative_chance:=greatest(0.25,least(0.75,party_spd/greatest(1,party_spd+enemy_spd)));
      turn_side:=case when random()<initiative_chance then 'party' else 'enemy' end;
      newstate:=jsonb_build_object('active',true,'enemy',enemy,'enemyRole',enemy_role,'boss',is_boss,'enemyHp',enemy_hp_max,'enemyMaxHp',enemy_hp_max,'enemyAtk',enemy_atk,'enemyDef',enemy_def,'enemySpd',enemy_spd,'enemyCrit',enemy_crit,'enemyEvade',enemy_evade,'partyHp',party_hp_json,'partyMaxHp',party_max_json,'attackCounts',attack_counts,'turn',turn_side,'initiative',turn_side,'initiativeChance',initiative_chance,'round',1,'damageDealt',0,'damageTaken',0,'crits',0,'dodges',0,'enemyCrits',0,'skills','[]'::jsonb,'lastAction',jsonb_build_object('type','encounter','turn',turn_side));
      newstate:=newstate||jsonb_build_object('enemySkill',coalesce(enemy_profile->'skill','{}'::jsonb),'enemyCounter',enemy_profile->>'counter','enemyArt',enemy_profile->>'art','contentVersion',15);
      event_text:=enemy||' 조우 · '||case when turn_side='party' then '몬스터 측 선공' else '인간 측 선공' end;
      log_entry:=jsonb_build_object('t',now(),'type','encounter','phase','조우','enemy',enemy,'enemyRole',enemy_role,'boss',is_boss,'initiative',turn_side,'initiativeChance',initiative_chance,'partyCount',party_n);
      update public.game_expeditions set phase='조우',battle_count=battle_count+1,exploration_count=exploration_count+1,event_state=jsonb_build_object('type','encounter','text',event_text,'enemy',enemy,'enemyRole',enemy_role,'boss',is_boss,'initiative',turn_side,'initiativeChance',initiative_chance,'t',now()),battle_state=newstate,updated_at=now() where id=e.id;
    end if;
  else
    enemy:=bs->>'enemy';enemy_role:=bs->>'enemyRole';is_boss:=coalesce((bs->>'boss')::boolean,false);enemy_hp:=coalesce((bs->>'enemyHp')::int,0);enemy_hp_max:=coalesce((bs->>'enemyMaxHp')::int,1);enemy_atk:=coalesce((bs->>'enemyAtk')::numeric,5);enemy_def:=coalesce((bs->>'enemyDef')::numeric,2);enemy_spd:=coalesce((bs->>'enemySpd')::numeric,9);enemy_crit:=coalesce((bs->>'enemyCrit')::numeric,0.05);enemy_evade:=coalesce((bs->>'enemyEvade')::numeric,0.03);party_hp_json:=coalesce(bs->'partyHp','{}'::jsonb);party_max_json:=coalesce(bs->'partyMaxHp','{}'::jsonb);attack_counts:=coalesce(bs->'attackCounts','{}'::jsonb);turn_side:=coalesce(bs->>'turn','party');round_i:=greatest(1,coalesce((bs->>'round')::int,1));dealt_total:=coalesce((bs->>'damageDealt')::int,0);taken_total:=coalesce((bs->>'damageTaken')::int,0);crits:=coalesce((bs->>'crits')::int,0);dodges:=coalesce((bs->>'dodges')::int,0);enemy_crits:=coalesce((bs->>'enemyCrits')::int,0);heal_total:=coalesce((bs->>'healingDone')::int,0);turn_heal:=0;skill_events:='[]'::jsonb;death_events:='[]'::jsonb;total_dmg:=0;
    if turn_side='party' then
      for mem in
        select m.*,coalesce(eq.eq_atk,0) eq_atk,coalesce(eq.eq_def,0) eq_def,coalesce(eq.eq_hp,0) eq_hp,coalesce(eq.eq_spd,0) eq_spd,coalesce(eq.eq_crit,0) eq_crit,coalesce(eq.eq_evade,0) eq_evade,coalesce(eq.human_damage,0) human_damage
        from public.game_expedition_members em join public.game_monsters m on m.id=em.monster_id
        left join lateral (select sum(d.atk*(1+coalesce(q.enhance_level,0)*0.08)) eq_atk,sum(d.def*(1+coalesce(q.enhance_level,0)*0.08)) eq_def,sum(d.hp*(1+coalesce(q.enhance_level,0)*0.08)) eq_hp,sum(d.spd*(1+coalesce(q.enhance_level,0)*0.08)) eq_spd,sum(d.crit*(1+coalesce(q.enhance_level,0)*0.08)) eq_crit,sum(d.evade*(1+coalesce(q.enhance_level,0)*0.08)) eq_evade,sum(d.human_damage*(1+coalesce(q.enhance_level,0)*0.08)) human_damage from public.game_monster_equipment q join public.game_item_defs d on d.id=q.item_id where q.monster_id=m.id) eq on true
        where em.expedition_id=e.id order by em.position
      loop
        current_hp:=coalesce((party_hp_json->>mem.id::text)::int,0);if current_hp<=0 then continue;end if;max_hp:=greatest(1,coalesce((party_max_json->>mem.id::text)::int,current_hp));
        growth:=case mem.growth_grade when 'S' then 1.21 when 'A' then 1.13 when 'B' then 1.06 else 1 end;lvl:=greatest(1,mem.level);
        matk:=mem.atk_base+(lvl-1)*2*growth+greatest(0,mem.talent-80)*0.22+mem.eq_atk;mspd:=mem.spd_base+(lvl-1)*0.18*growth+mem.eq_spd;mcrit:=mem.crit_base+mem.eq_crit;mhuman:=mem.human_damage;
        if mem.trait='재빠름' then mspd:=mspd*1.08;end if;
        if mem.personality='광전사' then matk:=matk*1.15;mcrit:=mcrit+0.05;elsif mem.personality='겁쟁이' then matk:=matk*0.95;mspd:=mspd*1.05;elsif mem.personality='인간혐오' then mhuman:=mhuman+0.12;elsif mem.personality='야행성' and (extract(hour from now() at time zone 'Asia/Seoul')>=18 or extract(hour from now() at time zone 'Asia/Seoul')<6) then matk:=matk*1.12;mspd:=mspd*1.12;end if;
        if mem.trait='야성' and current_hp<max_hp*0.4 then matk:=matk*1.20;end if;
        attack_no:=coalesce((attack_counts->>mem.id::text)::int,0)+1;attack_counts:=jsonb_set(attack_counts,array[mem.id::text],to_jsonb(attack_no),true);
        dmg:=0;heal_amount:=0;skill_fx:=public.game_trigger_monster_skill(mem.id,attack_no,current_hp::numeric/max_hp);
        skill_mult:=coalesce((skill_fx->>'damage_multiplier')::numeric,1);skill_ignore:=coalesce((skill_fx->>'defense_ignore')::numeric,0);skill_effect:=coalesce(nullif(skill_fx->>'effect_type',''),'damage');heal_ratio:=coalesce((skill_fx->>'heal_ratio')::numeric,0);armor_coeff:=case when skill_effect='magic' then 0.38 else 0.55 end;
        skill_name:=nullif(skill_fx->>'name','');skill_owner:=nullif(skill_fx->>'owner','');
        if skill_name is not null and skill_effect='heal' and heal_ratio>0 then
          heal_target_id:=null;heal_target_name:=null;
          select em.monster_id,m.name into heal_target_id,heal_target_name
          from public.game_expedition_members em join public.game_monsters m on m.id=em.monster_id
          where em.expedition_id=e.id
            and coalesce((party_hp_json->>em.monster_id::text)::int,0)>0
            and coalesce((party_hp_json->>em.monster_id::text)::int,0)<coalesce((party_max_json->>em.monster_id::text)::int,1)
          order by (coalesce((party_hp_json->>em.monster_id::text)::int,0)::numeric/greatest(1,coalesce((party_max_json->>em.monster_id::text)::int,1))) asc,em.position
          limit 1;
          if heal_target_id is not null then
            heal_before:=coalesce((party_hp_json->>heal_target_id::text)::int,0);heal_target_max:=greatest(1,coalesce((party_max_json->>heal_target_id::text)::int,heal_before));heal_after:=least(heal_target_max,heal_before+greatest(1,round(heal_target_max*heal_ratio)::int));heal_amount:=greatest(0,heal_after-heal_before);
            if heal_amount>0 then party_hp_json:=jsonb_set(party_hp_json,array[heal_target_id::text],to_jsonb(heal_after),true);turn_heal:=turn_heal+heal_amount;heal_total:=heal_total+heal_amount;skill_events:=skill_events||jsonb_build_array(jsonb_build_object('name',skill_name,'owner',skill_owner,'monsterId',mem.id,'attack',attack_no,'effect','heal','heal',heal_amount,'target',heal_target_name));end if;
          end if;
        end if;
        if random()>=least(0.35,enemy_evade+greatest(0,enemy_spd-mspd)*0.002) then
          dmg:=greatest(1,round(matk*(0.88+random()*0.24)*(1+mhuman)*skill_mult-enemy_def*armor_coeff*(1-least(0.90,skill_ignore)))::int);
          if random()<least(0.45,mcrit) then dmg:=round(dmg*1.7);crits:=crits+1;end if;
          enemy_hp:=greatest(0,enemy_hp-dmg);total_dmg:=total_dmg+dmg;dealt_total:=dealt_total+dmg;
          if skill_name is not null and skill_effect<>'heal' then skill_events:=skill_events||jsonb_build_array(jsonb_build_object('name',skill_name,'owner',skill_owner,'monsterId',mem.id,'attack',attack_no,'mult',skill_mult,'effect',skill_effect,'ignore',skill_ignore));end if;
        end if;
        exit when enemy_hp<=0;
      end loop;
      won:=enemy_hp<=0;
      last_action:=jsonb_build_object('type','party-turn','side','party','round',round_i,'damage',total_dmg,'healing',turn_heal,'skills',skill_events);
      if won then
        if is_boss then
          update public.game_stage_progress set boss_cleared=true,boss_ready=true,boss_cleared_at=now(),first_boss_cleared_at=coalesce(first_boss_cleared_at,now()),boss_victories=boss_victories+1,boss_last_result='win',
            boss_history=(select jsonb_agg(value order by ord) from jsonb_array_elements(jsonb_build_array(jsonb_build_object('at',now(),'result','win','enemy',enemy,'rounds',round_i,'party',party_hp_json))||boss_history) with ordinality h(value,ord) where ord<=20),updated_at=now() where player_id=e.player_id and site_id=e.site_id;
          update public.game_players set fame=fame+25,updated_at=now() where device_id=e.player_id;
        else
          update public.game_stage_progress set normal_wins=normal_wins+1,normal_battles=normal_battles+1,boss_ready=(boss_ready or boss_cleared or normal_battles+1>=500),updated_at=now() where player_id=e.player_id and site_id=e.site_id;
          update public.game_players set fame=fame+case when random()<0.08 then 1 else 0 end,updated_at=now() where device_id=e.player_id;
        end if;
        /* living-party-xp-v01320 */ select count(*) into living_n from public.game_expedition_members em where em.expedition_id=e.id and coalesce((party_hp_json->>em.monster_id::text)::int,0)>0;xp_each:=greatest(1,ceil((e.xp_per_kill*(case when is_boss then 5 else 1 end)*(1+0.10*greatest(0,greatest(1,living_n)-1)))::numeric/greatest(1,living_n))::int);
        for mem in select m.id,m.trait from public.game_expedition_members em join public.game_monsters m on m.id=em.monster_id where em.expedition_id=e.id and coalesce((party_hp_json->>m.id::text)::int,0)>0 loop xp_amt:=case when mem.trait='학습 본능' then round(xp_each*1.12)::int else xp_each end;perform public.game_apply_xp(mem.id,xp_amt);update public.game_monsters set kills=kills+1 where id=mem.id;end loop;
        update public.game_expeditions set kills=kills+1 where id=e.id;
        select greatest(coalesce(max(case when m.personality='약탈광' then 0.20 else 0 end),0),coalesce(max(case when m.trait='수집광' then 0.15 else 0 end),0)) into party_loot from public.game_expedition_members em join public.game_monsters m on m.id=em.monster_id where em.expedition_id=e.id;
        drops_json:=public.game_award_campaign_drops(e.id,public.game_roll_campaign_drops(e.loot,enemy,party_loot));
        select coalesce(sum(value::int),0) into loot_gained from jsonb_each_text(drops_json);
        event_text:=case when is_boss then enemy||' 보스 박멸 완료' else enemy||' 박멸 완료' end;
        if exists(select 1 from jsonb_each(drops_json) l join public.game_item_defs d on d.id=l.key where d.kind='equipment') then event_text:=event_text||' · 장비 발견!'; end if;
        newstate:=bs||jsonb_build_object('active',false,'result','win','enemyHp',0,'partyHp',party_hp_json,'partyMaxHp',party_max_json,'turn',null,'damageDealt',dealt_total,'healingDone',heal_total,'crits',crits,'skills',skill_events,'lastAction',last_action,'loot',loot_gained);
        log_entry:=jsonb_build_object('t',now(),'type','battle-end','phase','전투','enemy',enemy,'enemyRole',enemy_role,'boss',is_boss,'result','win','round',round_i,'damage',total_dmg,'damageDealt',dealt_total,'damageTaken',taken_total,'healingDone',heal_total,'skills',skill_events,'loot',loot_gained,'partyHp',party_hp_json,'partyMaxHp',party_max_json);
        newstate:=newstate||jsonb_build_object('drops',drops_json);
        log_entry:=log_entry||jsonb_build_object('drops',drops_json);
        update public.game_expeditions set phase='수색',event_state=jsonb_build_object('type','battle_end','text',event_text,'enemy',enemy,'enemyRole',enemy_role,'boss',is_boss,'result','win','t',now()),battle_state=newstate,updated_at=now() where id=e.id;
      else
        event_text:='몬스터 측 공격 · '||total_dmg||' 피해';
        newstate:=bs||jsonb_build_object('enemyHp',enemy_hp,'partyHp',party_hp_json,'attackCounts',attack_counts,'turn','enemy','round',round_i,'damageDealt',dealt_total,'healingDone',heal_total,'crits',crits,'skills',skill_events,'lastAction',last_action);
        log_entry:=jsonb_build_object('t',now(),'type','battle-turn','phase','전투','side','party','round',round_i,'enemy',enemy,'enemyRole',enemy_role,'damage',total_dmg,'healing',turn_heal,'enemyHp',enemy_hp,'enemyMaxHp',enemy_hp_max,'skills',skill_events,'partyHp',party_hp_json,'partyMaxHp',party_max_json);
        update public.game_expeditions set phase='전투',event_state=jsonb_build_object('type','battle_turn','side','party','text',event_text,'enemy',enemy,'enemyRole',enemy_role,'round',round_i,'t',now()),battle_state=newstate,updated_at=now() where id=e.id;
      end if;
    else
      enemy_skill:=coalesce(bs->'enemySkill','{}'::jsonb);
      enemy_skill_active:=coalesce((enemy_skill->>'every')::int,0)>0 and mod(round_i,greatest(1,coalesce((enemy_skill->>'every')::int,1)))=0;
      if enemy_skill_active then
        enemy_skill_damage:=coalesce((enemy_skill->>'multiplier')::numeric,1);
        enemy_skill_ignore:=least(0.9,greatest(0,coalesce((enemy_skill->>'ignore')::numeric,0)));
        enemy_healed:=least(enemy_hp_max-enemy_hp,greatest(0,round(enemy_hp_max*coalesce((enemy_skill->>'heal')::numeric,0))::int));
        enemy_hp:=enemy_hp+enemy_healed;
        bs:=bs||jsonb_build_object('enemyHp',enemy_hp);
      end if;
      select m.*,coalesce(eq.eq_def,0) eq_def,coalesce(eq.eq_spd,0) eq_spd,coalesce(eq.eq_evade,0) eq_evade,coalesce(rs.damage_reduction,0) role_reduction,coalesce(rs.taunt_weight,1) role_taunt into mem
      from public.game_expedition_members em join public.game_monsters m on m.id=em.monster_id
      left join lateral (select sum(d.def*(1+coalesce(q.enhance_level,0)*0.08)) eq_def,sum(d.spd*(1+coalesce(q.enhance_level,0)*0.08)) eq_spd,sum(d.evade*(1+coalesce(q.enhance_level,0)*0.08)) eq_evade from public.game_monster_equipment q join public.game_item_defs d on d.id=q.item_id where q.monster_id=m.id) eq on true
      left join public.game_skill_defs rs on rs.id=m.skill_id
      where em.expedition_id=e.id and coalesce((party_hp_json->>m.id::text)::int,0)>0
      order by (-ln(greatest(random(),0.000001))/greatest(0.10,coalesce(rs.taunt_weight,1))) asc limit 1;
      if not found then
        lost:=true;
      else
        target_id:=mem.id;target_name:=mem.name;hp_before:=coalesce((party_hp_json->>mem.id::text)::int,0);max_hp:=greatest(1,coalesce((party_max_json->>mem.id::text)::int,hp_before));growth:=case mem.growth_grade when 'S' then 1.21 when 'A' then 1.13 when 'B' then 1.06 else 1 end;lvl:=greatest(1,mem.level);
        mdef:=mem.def_base+(lvl-1)*0.8*growth+mem.eq_def;mspd:=mem.spd_base+(lvl-1)*0.18*growth+mem.eq_spd;mevade:=mem.evade_base+mem.eq_evade;
        if mem.trait='질긴 가죽' then mdef:=mdef*1.10;elsif mem.trait='재빠름' then mspd:=mspd*1.08;mevade:=mevade+0.02;end if;
        if mem.personality='광전사' then mdef:=mdef*0.90;elsif mem.personality='겁쟁이' then mspd:=mspd*1.05;mevade:=mevade+0.08;elsif mem.personality='침착' then mdef:=mdef*1.10;mevade:=mevade+0.02;elsif mem.personality='야행성' and (extract(hour from now() at time zone 'Asia/Seoul')>=18 or extract(hour from now() at time zone 'Asia/Seoul')<6) then mspd:=mspd*1.12;end if;
        dmg:=0;
        if random()>=least(0.35,least(0.35,mevade)+greatest(0,mspd-enemy_spd)*0.002) then dmg:=greatest(1,round(enemy_atk*enemy_skill_damage*(0.88+random()*0.24)-mdef*0.58*(1-enemy_skill_ignore))::int);if random()<enemy_crit then dmg:=round(dmg*1.65);enemy_crits:=enemy_crits+1;end if;if dmg>0 and coalesce(mem.role_reduction,0)>0 then dmg:=greatest(1,round(dmg*(1-least(0.55,mem.role_reduction)))::int);end if;else dodges:=dodges+1;end if;
        hp_after:=greatest(0,hp_before-dmg);party_hp_json:=jsonb_set(party_hp_json,array[mem.id::text],to_jsonb(hp_after),true);taken_total:=taken_total+dmg;
        if hp_before>0 and hp_after<=0 then xp_lost:=public.game_apply_death_xp_penalty(mem.id);death_events:=jsonb_build_array(jsonb_build_object('monsterId',mem.id,'name',mem.name,'xpLost',xp_lost));end if;
        select count(*) into living_n from public.game_expedition_members em where em.expedition_id=e.id and coalesce((party_hp_json->>em.monster_id::text)::int,0)>0;
        lost:=living_n<=0;
      end if;
      last_action:=jsonb_build_object('type','enemy-turn','side','enemy','round',round_i,'targetId',target_id,'target',target_name,'damage',dmg,'tankReduction',coalesce(mem.role_reduction,0),'tauntWeight',coalesce(mem.role_taunt,1),'deaths',death_events);
      last_action:=last_action||jsonb_build_object('enemySkill',case when enemy_skill_active then enemy_skill->>'name' else null end,'enemyHealing',enemy_healed);
      if lost then
        if is_boss then
          update public.game_stage_progress
          set boss_last_result='loss',
            boss_history=(select jsonb_agg(value order by ord) from jsonb_array_elements(jsonb_build_array(jsonb_build_object('at',now(),'result','loss','enemy',enemy,'rounds',round_i,'party',party_hp_json))||boss_history) with ordinality h(value,ord) where ord<=20),updated_at=now()
          where player_id=e.player_id and site_id=e.site_id;
          event_text:=enemy||'에게 보스전 패배 · 재정비 후 탐험을 계속하면 다시 조우할 수 있습니다';
        else
          update public.game_stage_progress set normal_battles=normal_battles+1,boss_ready=(boss_ready or boss_cleared or normal_battles+1>=500),updated_at=now() where player_id=e.player_id and site_id=e.site_id;
          event_text:=enemy||'에게 전투 패배';
        end if;
        newstate:=bs||jsonb_build_object('active',false,'result','loss','partyHp',party_hp_json,'turn',null,'round',round_i,'damageTaken',taken_total,'dodges',dodges,'enemyCrits',enemy_crits,'skills','[]'::jsonb,'lastAction',last_action);
        log_entry:=jsonb_build_object('t',now(),'type','battle-end','phase','전투','side','enemy','round',round_i,'enemy',enemy,'enemyRole',enemy_role,'boss',is_boss,'result','loss','damage',dmg,'damageDealt',dealt_total,'damageTaken',taken_total,'deaths',death_events,'partyHp',party_hp_json,'partyMaxHp',party_max_json);
        update public.game_expeditions set active=false,phase='전멸 · 복귀',event_state=jsonb_build_object('type','battle_end','text',event_text,'enemy',enemy,'enemyRole',enemy_role,'boss',is_boss,'result','loss','deaths',death_events,'t',now()),battle_state=newstate,updated_at=now() where id=e.id;
      else
        event_text:=enemy||' 공격 · '||coalesce(target_name,'몬스터')||'에게 '||dmg||' 피해'||case when jsonb_array_length(death_events)>0 then ' · 전투불능' else '' end;
        if enemy_skill_active then event_text:=event_text||' · '||(enemy_skill->>'name')||case when enemy_healed>0 then ' · 적 HP +'||enemy_healed else '' end; end if;
        newstate:=bs||jsonb_build_object('partyHp',party_hp_json,'turn','party','round',round_i+1,'damageTaken',taken_total,'dodges',dodges,'enemyCrits',enemy_crits,'skills','[]'::jsonb,'lastAction',last_action);
        log_entry:=jsonb_build_object('t',now(),'type','battle-turn','phase','전투','side','enemy','round',round_i,'enemy',enemy,'enemyRole',enemy_role,'target',target_name,'targetId',target_id,'damage',dmg,'deaths',death_events,'partyHp',party_hp_json,'partyMaxHp',party_max_json);
        update public.game_expeditions set phase='전투',event_state=jsonb_build_object('type','battle_turn','side','enemy','text',event_text,'enemy',enemy,'enemyRole',enemy_role,'target',target_name,'damage',dmg,'deaths',death_events,'round',round_i,'t',now()),battle_state=newstate,updated_at=now() where id=e.id;
      end if;
    end if;
  end if;

  if enemy_skill_active then log_entry:=log_entry||jsonb_build_object('enemySkill',enemy_skill->>'name','enemyHealing',enemy_healed); end if;
  newlog:=jsonb_build_array(log_entry)||coalesce(e.battle_log,'[]'::jsonb);
  select coalesce(jsonb_agg(value order by ord),'[]'::jsonb) into newlog from jsonb_array_elements(newlog) with ordinality a(value,ord) where ord<=20;
  update public.game_expeditions set battle_log=newlog where id=e.id;
  return log_entry;
end
$function$;
